#pragma once

#include <cstdint>
#include <cstring>
#include <string>

#include "mdParameterHelp.h"

// Plain-language help for Machinedrum OS 1.63 machines and DATA ENTRY parameters. The LCD is
// identified through lcdText hashes (field labels with lcdText::inkHash, machine names with
// lcdText::hash over g_mdMachineName); descriptions are paraphrased from the owner's manual.
namespace mdJucePlugin::machinedrumHelp
{
	using parameterHelp::LabelHash;
	using parameterHelp::Entry;

	// Machines whose SYNTHESIS parameters mean the same thing share a family.
	enum class Family : uint8_t
	{
		Gnd, Trx, Efm, E12, PhysicallyInformed, Input, Midi,
		ControlAll, Control8, ControlEcho, ControlReverb, ControlEq, ControlDynamix,
		Rom, RamRecord,
	};

	// Generated by mdmmLcdCapture from Machinedrum OS 1.63 screens. Bracketed labels are drawn
	// inverted (CTR-AL).
	inline constexpr LabelHash g_labelHashes[] =
	{
		{ 0xdd4a5dff6346605bull, "AMD" },
		{ 0x871b76f678a409e6ull, "AMF" },
		{ 0x9ccd7ade7b3cf1b9ull, "EQF" },
		{ 0x3a42b17afa39f083ull, "EQG" },
		{ 0x7caca78a15331d9aull, "FLTF" },
		{ 0x9d8f3c7051195c9eull, "FLTW" },
		{ 0x9e8c7a8f019b1252ull, "FLTQ" },
		{ 0x36143b7d7cc21971ull, "SRR" },
		{ 0x7933f80a4d7320f9ull, "DIST" },
		{ 0x9e7f4adf197a52abull, "VOL" },
		{ 0x6fa9f7f34586bcbeull, "PAN" },
		{ 0xb609a43c556e8aa2ull, "DEL" },
		{ 0x2b5b8482ceb63922ull, "REV" },
		{ 0x7661e3cb67261fe3ull, "LFOS" },
		{ 0x47f7fdb098f70634ull, "LFOD" },
		{ 0x35723df68dba1651ull, "LFOM" },
		{ 0xc8bb6ee6c0bde6cdull, "PTCH" },
		{ 0xf9d8b8a14988b0b4ull, "DEC" },
		{ 0x14811d48ed21058cull, "RAMP" },
		{ 0x9eb08717ee26fcd5ull, "RDEC" },
		{ 0x4feb51b67698b5ebull, "UP" },
		{ 0x74f98ec301280810ull, "UVAL" },
		{ 0xbfd3b73dfa54a029ull, "DOWN" },
		{ 0xa185d92ded1a68abull, "DVAL" },
		{ 0xd3b53541c5c53570ull, "STRT" },
		{ 0xefc801cdf4302eb0ull, "NOIS" },
		{ 0x3a149868efd02e75ull, "HARM" },
		{ 0xc796721671a572adull, "CLIP" },
		{ 0x8a67a2ec0c1a7a48ull, "BUMP" },
		{ 0xe3f365c75fc72f43ull, "BENV" },
		{ 0x62447c6e54047125ull, "SNAP" },
		{ 0xe96f73e9eb95e294ull, "TONE" },
		{ 0xd6fc0934fc3cb6b3ull, "TUNE" },
		{ 0x784c1ad6aaaeebd5ull, "DAMP" },
		{ 0x1c3140fc224fa8f0ull, "DTYP" },
		{ 0x122e009afc8cd8a1ull, "CLPY" },
		{ 0x4c48280aa19a479cull, "HARD" },
		{ 0xd433a8683101bfb2ull, "RICH" },
		{ 0x4cda4929f011ad3full, "RATE" },
		{ 0x7bb12e2491845816ull, "ROOM" },
		{ 0xe423b8acd5e8a860ull, "RSIZ" },
		{ 0x8fa7ef1bcf27362dull, "RTUN" },
		{ 0x7b21dd56bccd9230ull, "ENH" },
		{ 0xd51f252eaf91743full, "GAP" },
		{ 0xd1f1d4a95be0d756ull, "HPF" },
		{ 0x6787b29f0799ec7aull, "LPF" },
		{ 0x13a2128b92eb7bebull, "MTAL" },
		{ 0x826c6e36bfadb8cfull, "TOP" },
		{ 0x39b40fd92fb9d7ebull, "TTUN" },
		{ 0x4173efa5672c00beull, "SIZE" },
		{ 0xceb7e728f906939dull, "PEAK" },
		{ 0x45baec5663df0dceull, "ATT" },
		{ 0xe6f536f44cc86681ull, "SUS" },
		{ 0x39856194bbf53c87ull, "RATL" },
		{ 0x0de678714da6f8e5ull, "RTYP" },
		{ 0x99e825d4d8e7b34aull, "DUAL" },
		{ 0x7906d70fcaf03882ull, "CLIC" },
		{ 0x9eeff4996298e7baull, "HOLD" },
		{ 0xa914672ba1de6371ull, "TICK" },
		{ 0x22f79b19d8b762c3ull, "DIRT" },
		{ 0x17802aba715b7f2full, "MOD" },
		{ 0xacb34d508344079aull, "MFRQ" },
		{ 0x21187381d543a61dull, "MDEC" },
		{ 0xf942cc41521eaa3cull, "MFB" },
		{ 0x8b080efe802bfceaull, "NDEC" },
		{ 0xe85ebbde47cdf65dull, "CLPS" },
		{ 0xaa875134b590d099ull, "CDEC" },
		{ 0x58eda507e2ab3b1aull, "SNAR" },
		{ 0x718ee7c44908dfe5ull, "SPTC" },
		{ 0xd68ecbefd1b89e5full, "SDEC" },
		{ 0xfb6897b304b69e20ull, "SMOD" },
		{ 0xf9e77465a7ed4671ull, "FB" },
		{ 0x848f40f20f09831aull, "TREM" },
		{ 0xd5238962aadd0ee0ull, "TFRQ" },
		{ 0x9f8fb23fe843d476ull, "SPLN" },
		{ 0x151e951945dbf5c6ull, "RTRG" },
		{ 0xd4c47d83324a5d46ull, "RTIM" },
		{ 0xfa5514bc571957a9ull, "BEND" },
		{ 0xee77a2b04bb11d73ull, "HP" },
		{ 0xcaeacf0e21d6e141ull, "RING" },
		{ 0xee8eb10df7fbbd06ull, "HPQ" },
		{ 0x703057f3f9ddc02cull, "STOP" },
		{ 0xc537383b87c9817full, "BELL" },
		{ 0x367e203e0e4ba3c7ull, "REAL" },
		{ 0xf0b104ee50b6b540ull, "SLEW" },
		{ 0x88deea69c90b3031ull, "BC" },
		{ 0xbb46f35401fd581dull, "HAMR" },
		{ 0x781d6d59b661fc13ull, "TENS" },
		{ 0x57a0a7197c1b7c82ull, "RVOL" },
		{ 0xf8efc51c8589698bull, "POS" },
		{ 0x15067bd7c868febdull, "GRNS" },
		{ 0xab92494947768dbfull, "GLEN" },
		{ 0x3ecafc67e451ea85ull, "AG" },
		{ 0x37d6437dca4ec3b5ull, "AU" },
		{ 0x0e4f02342cbb4115ull, "BR" },
		{ 0x64edefbacc9d09caull, "GRAB" },
		{ 0x0b442bf397573619ull, "CLSN" },
		{ 0x5459135548cfcb13ull, "CLOS" },
		{ 0x82ccda40395e8a09ull, "GATE" },
		{ 0xd521510ea70d45faull, "ATCK" },
		{ 0xffdb878304dff3c6ull, "HLD" },
		{ 0x491f100b7796497cull, "ALEV" },
		{ 0xd9d730b88a547bceull, "FATK" },
		{ 0xd393fa5cf0ccfecfull, "FHLD" },
		{ 0x517d5b5052730eb9ull, "FDEC" },
		{ 0x830a527959ad58ceull, "FDPH" },
		{ 0xde4afbab615478a6ull, "FFRQ" },
		{ 0xa5f38f540fcb10b6ull, "FQ" },
		{ 0xc590a16805bc69a2ull, "AHLD" },
		{ 0x317f3f69ab3f9b8cull, "ADEC" },
		{ 0xe994795a10fcd38cull, "NOTE" },
		{ 0x99e8766315b38c3full, "N2" },
		{ 0x00f25850f9503b43ull, "N3" },
		{ 0xe37e15695ebe3914ull, "LEN" },
		{ 0x88e538ae8a76f97cull, "VEL" },
		{ 0x01442995410878a6ull, "PB" },
		{ 0x61c54a71a81033deull, "MW" },
		{ 0x34f4f12b9e23a3fdull, "AT" },
		{ 0x7da458138c9dc6beull, "CC1D" },
		{ 0xccbef65e9fded1dcull, "CC1V" },
		{ 0x06099e08a1c29c49ull, "CC2D" },
		{ 0x8f95ef586a9da0abull, "CC2V" },
		{ 0x83703834411b1e8dull, "CC3D" },
		{ 0x0148444f7e21d987ull, "CC3V" },
		{ 0x58458f8b66fc0e3bull, "CC4D" },
		{ 0xc46bf9fca4f81f71ull, "CC4V" },
		{ 0x924b46a8a205fce9ull, "CC5D" },
		{ 0x4db1af573fea288bull, "CC5V" },
		{ 0x39ac9614070db7aaull, "CC6D" },
		{ 0xa586da841f3ef650ull, "CC6V" },
		{ 0xc232a432b9e7db9dull, "PCHG" },
		{ 0x9bb6ec7cde780a4full, "[SYN1]" },
		{ 0xa409dd05e7bc3350ull, "[SYN2]" },
		{ 0xaae00ac75a7613c0ull, "[SYN3]" },
		{ 0x5e0692d276b9b4c6ull, "[SYN4]" },
		{ 0xf6b0b48438bab442ull, "[SYN5]" },
		{ 0xbdf7b49ebe07a527ull, "[SYN6]" },
		{ 0x63f51a15d0a0bb06ull, "[SYN7]" },
		{ 0xc0e8df605d29a8caull, "[SYN8]" },
		{ 0x07c18e30b65f3e50ull, "[AMD]" },
		{ 0x80dac0406589b459ull, "[AMF]" },
		{ 0x379d4cfc61900272ull, "[EQF]" },
		{ 0xd36c686aa18f5ee0ull, "[EQG]" },
		{ 0x61dc6b89a4d30f7dull, "[FLTF]" },
		{ 0x2a7ec45cd8f8a061ull, "[FLTW]" },
		{ 0x294b3dbd775bc0fdull, "[FLTQ]" },
		{ 0x3cc523024b295a88ull, "[SRR]" },
		{ 0x14581400c0be88a2ull, "[DIST]" },
		{ 0xe2ffe499e09c3f48ull, "[VOL]" },
		{ 0xbef4cb487a6ec8b1ull, "[PAN]" },
		{ 0x465bcac3b9ab26edull, "[DEL]" },
		{ 0x15772b68601eb461ull, "[REV]" },
		{ 0x2d779de7466f6216ull, "[LFOS]" },
		{ 0x51f4ac5dc44a6447ull, "[LFOD]" },
		{ 0x782cd8b5fbf06bacull, "[LFOM]" },
		{ 0x8096cc7d685d76c4ull, "P1" },
		{ 0x13cfaa5c13dcc9dbull, "P2" },
		{ 0x8e65203ef73ac82full, "P3" },
		{ 0x8dbcb37f34131289ull, "P4" },
		{ 0xf24ff541381664cbull, "P5" },
		{ 0xc9720a55294524e0ull, "P6" },
		{ 0xa8130e26c7860c8bull, "P7" },
		{ 0x2f98e54b0081386full, "P8" },
		{ 0x3a8b7002feefc100ull, "TIME" },
		{ 0x64459c217938fe3dull, "MONO" },
		{ 0xa59319687e2a5ab4ull, "LEV" },
		{ 0xbc0aa47c5aeef4d3ull, "DVOL" },
		{ 0x7c92ce51e0c8e4daull, "PRED" },
		{ 0xdc89b032256f6ebfull, "LP" },
		{ 0x534ca6e9beffc9c4ull, "LF" },
		{ 0x2b3e7e6f091f305eull, "LG" },
		{ 0x72d1ca8900e12734ull, "HF" },
		{ 0x74d90b307723e3a6ull, "HG" },
		{ 0x47d6d260643686edull, "PF" },
		{ 0x637908ac945e2f73ull, "PG" },
		{ 0xa31debf83a2df6c5ull, "PQ" },
		{ 0x79597ee9c4db9758ull, "GAIN" },
		{ 0x9ed448683047449bull, "REL" },
		{ 0xc61841b21030bf0full, "TRHD" },
		{ 0x35fcbde1873ee7d3ull, "RTIO" },
		{ 0x2966c13abc792c86ull, "KNEE" },
		{ 0x395e6831a8444585ull, "OUTG" },
		{ 0x89215dd728f0cd97ull, "MIX" },
		{ 0xa2868246e48baa68ull, "BRR" },
		{ 0x76193c4801d47bfbull, "END" },
		{ 0x59b6d61ce14e5fa5ull, "MLEV" },
		{ 0x004e70c9f91e7a82ull, "MBAL" },
		{ 0xb3f872c3f005f117ull, "ILEV" },
		{ 0xfd0ff0784b4566e8ull, "IBAL" },
		{ 0x496b6879f0c4310bull, "CUE1" },
		{ 0x202486df02059ef8ull, "CUE2" },
	};

	// Machine key: the Appendix C SysEx number, plus 0x100 for the UW set (ROM and RAM).
	struct MachineHash
	{
		uint64_t hash;
		uint16_t key;
	};

	inline constexpr MachineHash g_machineHashes[] =
	{
		{ 0x50a3a218ee70d52eull, 0x000 },
		{ 0x198bbfe732ad57afull, 0x001 },
		{ 0x70615208d22e5bebull, 0x002 },
		{ 0xb0a9ff168366b1d0ull, 0x003 },
		{ 0xd6d108e916a9b560ull, 0x010 },
		{ 0x23d53071a71dfc2dull, 0x011 },
		{ 0x31e4d93158a96382ull, 0x012 },
		{ 0xa1aa088ff4ad50e5ull, 0x013 },
		{ 0xc89b6b132184e1f4ull, 0x014 },
		{ 0xd2450172f1bed34dull, 0x015 },
		{ 0x1c7d50a8c7ee5188ull, 0x016 },
		{ 0xba627c47e70c8721ull, 0x017 },
		{ 0xb29af2daa8835780ull, 0x018 },
		{ 0x51ff204e3a16ec6bull, 0x019 },
		{ 0x00b6aa3a30663214ull, 0x01a },
		{ 0x3c82e3ec4ac392e0ull, 0x01b },
		{ 0x7fb724960a9f60bfull, 0x01c },
		{ 0xa30add035f4cedfaull, 0x020 },
		{ 0xfa237531fc3b27ffull, 0x021 },
		{ 0xbeeae9e2d8406fbcull, 0x022 },
		{ 0x88fd88d27064ce13ull, 0x023 },
		{ 0xee60b3cb8d8192c6ull, 0x024 },
		{ 0x18288ad636843887ull, 0x025 },
		{ 0x41cf0eed30f40134ull, 0x026 },
		{ 0xe75183aff5961ec2ull, 0x027 },
		{ 0x86906dfebc1fa5a9ull, 0x030 },
		{ 0xe234dbf0ffa5ce4cull, 0x031 },
		{ 0xa26b95e78fd3645bull, 0x032 },
		{ 0x01d87b04a9150d7full, 0x033 },
		{ 0x4f0e0d7d298fa6b0ull, 0x034 },
		{ 0xb5b0545b44380611ull, 0x035 },
		{ 0x72e19065286cde18ull, 0x036 },
		{ 0x68305aea4a6eba6dull, 0x037 },
		{ 0xf02802c415cdfa14ull, 0x038 },
		{ 0xeb92622be1c5b5efull, 0x039 },
		{ 0x8377421696a9c1abull, 0x03a },
		{ 0x58efd24b7f8d3268ull, 0x03b },
		{ 0xb115c4e1c6413a18ull, 0x03c },
		{ 0xfd5da756cac60fa5ull, 0x03d },
		{ 0x4ec5b74331a4b10full, 0x03e },
		{ 0x875ab29156b35ffcull, 0x03f },
		{ 0x148b1455f5ad2617ull, 0x040 },
		{ 0x41af0e6cc611c38eull, 0x041 },
		{ 0x6f0d515fb81f00b3ull, 0x042 },
		{ 0x116f1887b2bcac63ull, 0x043 },
		{ 0xd419bb8bddaa81c0ull, 0x044 },
		{ 0xc6494a9e980aab4full, 0x045 },
		{ 0xdaa6329cb6e43e71ull, 0x046 },
		{ 0x8fcadd904dc3c1b9ull, 0x047 },
		{ 0x8d6d194e7bd55551ull, 0x048 },
		{ 0xa5684d961557486full, 0x050 },
		{ 0xe95d2e159715bbb1ull, 0x051 },
		{ 0x0a3638ace4dcfb91ull, 0x052 },
		{ 0xd7c1d80a86d480afull, 0x053 },
		{ 0x13fce8313fa03947ull, 0x054 },
		{ 0xb0da7cbbb5849775ull, 0x055 },
		{ 0x13316e5632601c65ull, 0x060 },
		{ 0x9c009eff09037116ull, 0x061 },
		{ 0x0183484dec86f4a6ull, 0x062 },
		{ 0x956ca17c4793c278ull, 0x063 },
		{ 0x08115a277a86654eull, 0x064 },
		{ 0x2cb3813c524dba45ull, 0x065 },
		{ 0xfa2946581eb4ff4aull, 0x066 },
		{ 0x91d3d29d53805cfeull, 0x067 },
		{ 0xb675f9b22b47b1f5ull, 0x068 },
		{ 0x4e07f724f43b923dull, 0x069 },
		{ 0x2cb6b8e9fa96203dull, 0x06a },
		{ 0x5919c9aeb1b66cdaull, 0x06b },
		{ 0xbe9c72fd9539f06aull, 0x06c },
		{ 0xfabe022a4e541618ull, 0x06d },
		{ 0x1475b6dcb80bbe7aull, 0x06e },
		{ 0x3917ddf18fd31371ull, 0x06f },
		{ 0x027825cc7368ac1bull, 0x070 },
		{ 0x7e956c4c7f08d3cdull, 0x071 },
		{ 0xe90fd5d3eb04fd7eull, 0x078 },
		{ 0x2e1543d797671275ull, 0x079 },
		{ 0xf6d998719b1c0d4aull, 0x07a },
		{ 0xa834f5e2a6775983ull, 0x07b },
		{ 0xde544ebc69559641ull, 0x100 },
		{ 0x6e78be723b4bb0daull, 0x101 },
		{ 0x590f59e5371545c2ull, 0x102 },
		{ 0x13f309138339a748ull, 0x103 },
		{ 0xd3913b0abdb391ffull, 0x104 },
		{ 0xa320882039034884ull, 0x105 },
		{ 0xf774f1ec78ce71abull, 0x106 },
		{ 0x22e18e5491d5347bull, 0x107 },
		{ 0xf270db6a0d24eb00ull, 0x108 },
		{ 0x4aeaf881b4b6b679ull, 0x109 },
		{ 0x3ef6a1d2a0c4bacdull, 0x10a },
		{ 0x35a046e8c27cec0aull, 0x10b },
		{ 0x5baa48057db29e07ull, 0x10c },
		{ 0x642476d6350b3614ull, 0x10d },
		{ 0xc5177823532c1517ull, 0x10e },
		{ 0x99b1a9a92ce01fd5ull, 0x10f },
		{ 0x706e1e6b5eefd3e6ull, 0x110 },
		{ 0xd245f64789912122ull, 0x111 },
		{ 0xe2538d7722b148f5ull, 0x112 },
		{ 0x071ca136e958d83aull, 0x113 },
		{ 0xcd4ef63a87a8874aull, 0x114 },
		{ 0x5698844a1d80ae41ull, 0x115 },
		{ 0x6c01e8d721b71959ull, 0x116 },
		{ 0x04feed50dcee7227ull, 0x117 },
		{ 0x2cf36d5b5a84ea31ull, 0x118 },
		{ 0x1ce5d62bc164c25eull, 0x119 },
		{ 0x3caa34f39d7e7280ull, 0x11a },
		{ 0x07209c61fda9eb45ull, 0x11b },
		{ 0x32866adc23f5e087ull, 0x11c },
		{ 0x20df7e4153e88fa2ull, 0x11d },
		{ 0x37783a4fbc3cf1baull, 0x11e },
		{ 0x705b6154881065a9ull, 0x11f },
		{ 0xe7ad895e028ede1eull, 0x120 },
		{ 0x8df15fc3076b7f49ull, 0x121 },
		{ 0xfb2a549f4de97e0dull, 0x122 },
		{ 0x1a38bbd6842310aaull, 0x123 },
		{ 0x96e57dec936124e1ull, 0x125 },
		{ 0xce960ff89ec74e87ull, 0x126 },
		{ 0xb4b61287a09f8d1aull, 0x127 },
		{ 0x6d7592e338a41bb8ull, 0x128 },
		{ 0x0b3c9414ab65de56ull, 0x130 },
		{ 0xf586a7920dce6910ull, 0x131 },
		{ 0x4a4b0f9072980d7eull, 0x132 },
		{ 0xd4486c57ffe1ea7dull, 0x133 },
		{ 0x32328c768de5aed2ull, 0x134 },
		{ 0x4075765d0afd92a6ull, 0x135 },
		{ 0xca72d32498476fa5ull, 0x136 },
		{ 0x2ca5b778585b1febull, 0x137 },
		{ 0xb195c6b831dbbc83ull, 0x138 },
		{ 0xc6160f8d193679acull, 0x139 },
		{ 0x2a52093d2821be3cull, 0x13a },
		{ 0x5fd1620a344e40b6ull, 0x13b },
		{ 0x696084b8ef53ed64ull, 0x13c },
		{ 0x4630b3665478e7cbull, 0x13d },
		{ 0x202efcb3e464fec8ull, 0x13e },
		{ 0x5f8aeb8587b9728cull, 0x13f },
	};

	struct Machine
	{
		uint16_t first, last;	// key range
		uint8_t number;			// shown number of the first key in a numbered range (MID-01, ROM-25), else 0
		Family family;
		const char* lcdName;	// without the number for numbered ranges
		const char* name;
		const char* description;
	};

	namespace text
	{
		inline constexpr const char* trx = "TRX: classic analogue drum machine-style synthesis.";
		inline constexpr const char* efm = "EFM: Elektron's Enhanced Feedback Modulation, from realistic drums to chaotic effects.";
		inline constexpr const char* e12 = "E12: carefully processed sampled percussion.";
		inline constexpr const char* pi = "P-I: physically informed models of acoustic drums.";
		inline constexpr const char* gate = "Passes external audio through a gate. It ignores trigs, but needs one trig to become active.";
		inline constexpr const char* follower = "Envelope low-pass filter follower for external audio. It ignores trigs, but needs one trig to become active.";
		inline constexpr const char* envelope = "Plays external audio like a drum: trigs fire its amplitude and filter envelopes.";
		inline constexpr const char* masterControl = " on the SYNTHESIS page, so it can be locked and sequenced. Its LFO controls are on ROUTING.";
	}

	inline constexpr Machine g_machines[] =
	{
		{ 0, 0, 0, Family::Gnd, "GND---", "Empty", "No sound. Leaves the track free." },
		{ 1, 1, 0, Family::Gnd, "GND-SN", "Sine", "A plain sine tone with a pitch ramp, for adding tonality." },
		{ 2, 2, 0, Family::Gnd, "GND-NS", "Noise", "Plain noise with a decay control." },
		{ 3, 3, 0, Family::Gnd, "GND-IM", "Impulse", "A single impulse with adjustable positive and negative phases." },
		{ 16, 16, 0, Family::Trx, "TRX-BD", "TRX bass drum", text::trx },
		{ 17, 17, 0, Family::Trx, "TRX-SD", "TRX snare drum", text::trx },
		{ 18, 18, 0, Family::Trx, "TRX-XT", "TRX tom", text::trx },
		{ 19, 19, 0, Family::Trx, "TRX-CP", "TRX clap", text::trx },
		{ 20, 20, 0, Family::Trx, "TRX-RS", "TRX rim shot", text::trx },
		{ 21, 21, 0, Family::Trx, "TRX-CB", "TRX cowbell", text::trx },
		{ 22, 22, 0, Family::Trx, "TRX-CH", "TRX closed hi-hat", text::trx },
		{ 23, 23, 0, Family::Trx, "TRX-OH", "TRX open hi-hat", text::trx },
		{ 24, 24, 0, Family::Trx, "TRX-CY", "TRX cymbal", text::trx },
		{ 25, 25, 0, Family::Trx, "TRX-MA", "TRX maracas", text::trx },
		{ 26, 26, 0, Family::Trx, "TRX-CL", "TRX claves", text::trx },
		{ 27, 27, 0, Family::Trx, "TRX-XC", "TRX congas", text::trx },
		{ 28, 28, 0, Family::Trx, "TRX-B2", "TRX bass drum 2", text::trx },
		{ 32, 32, 0, Family::Efm, "EFM-BD", "EFM bass drum", text::efm },
		{ 33, 33, 0, Family::Efm, "EFM-SD", "EFM snare drum", text::efm },
		{ 34, 34, 0, Family::Efm, "EFM-XT", "EFM tom", text::efm },
		{ 35, 35, 0, Family::Efm, "EFM-CP", "EFM clap", text::efm },
		{ 36, 36, 0, Family::Efm, "EFM-RS", "EFM rim shot", text::efm },
		{ 37, 37, 0, Family::Efm, "EFM-CB", "EFM cowbell", text::efm },
		{ 38, 38, 0, Family::Efm, "EFM-HH", "EFM hi-hat", text::efm },
		{ 39, 39, 0, Family::Efm, "EFM-CY", "EFM cymbal", text::efm },
		{ 48, 48, 0, Family::E12, "E12-BD", "E12 bass drum", text::e12 },
		{ 49, 49, 0, Family::E12, "E12-SD", "E12 snare drum", text::e12 },
		{ 50, 50, 0, Family::E12, "E12-HT", "E12 high tom", text::e12 },
		{ 51, 51, 0, Family::E12, "E12-LT", "E12 low tom", text::e12 },
		{ 52, 52, 0, Family::E12, "E12-CP", "E12 clap", text::e12 },
		{ 53, 53, 0, Family::E12, "E12-RS", "E12 rim shot", text::e12 },
		{ 54, 54, 0, Family::E12, "E12-CB", "E12 cowbell", text::e12 },
		{ 55, 55, 0, Family::E12, "E12-CH", "E12 closed hi-hat", text::e12 },
		{ 56, 56, 0, Family::E12, "E12-OH", "E12 open hi-hat", text::e12 },
		{ 57, 57, 0, Family::E12, "E12-RC", "E12 ride cymbal", text::e12 },
		{ 58, 58, 0, Family::E12, "E12-CC", "E12 crash cymbal", text::e12 },
		{ 59, 59, 0, Family::E12, "E12-BR", "E12 brushed snare", text::e12 },
		{ 60, 60, 0, Family::E12, "E12-TA", "E12 tambourine", text::e12 },
		{ 61, 61, 0, Family::E12, "E12-TR", "E12 triangle", text::e12 },
		{ 62, 62, 0, Family::E12, "E12-SH", "E12 shaker", text::e12 },
		{ 63, 63, 0, Family::E12, "E12-BC", "E12 bongo conga", text::e12 },
		{ 64, 64, 0, Family::PhysicallyInformed, "P-I-BD", "P-I bass drum", text::pi },
		{ 65, 65, 0, Family::PhysicallyInformed, "P-I-SD", "P-I snare drum", text::pi },
		{ 66, 66, 0, Family::PhysicallyInformed, "P-I-MT", "P-I tom", text::pi },
		{ 67, 67, 0, Family::PhysicallyInformed, "P-I-ML", "P-I metallica", text::pi },
		{ 68, 68, 0, Family::PhysicallyInformed, "P-I-MA", "P-I maracas", text::pi },
		{ 69, 69, 0, Family::PhysicallyInformed, "P-I-RS", "P-I rim shot", text::pi },
		{ 70, 70, 0, Family::PhysicallyInformed, "P-I-RC", "P-I ride cymbal", text::pi },
		{ 71, 71, 0, Family::PhysicallyInformed, "P-I-CC", "P-I crash cymbal", text::pi },
		{ 72, 72, 0, Family::PhysicallyInformed, "P-I-HH", "P-I hi-hat", text::pi },
		{ 80, 80, 0, Family::Input, "INP-GA", "Input gate A", text::gate },
		{ 81, 81, 0, Family::Input, "INP-GB", "Input gate B", text::gate },
		{ 82, 82, 0, Family::Input, "INP-FA", "Input filter follower A", text::follower },
		{ 83, 83, 0, Family::Input, "INP-FB", "Input filter follower B", text::follower },
		{ 84, 84, 0, Family::Input, "INP-EA", "Input envelope A", text::envelope },
		{ 85, 85, 0, Family::Input, "INP-EB", "Input envelope B", text::envelope },
		{ 96, 111, 1, Family::Midi, "MID-", "MIDI machine", "Plays external gear over MIDI OUT on the channel with this machine's number. Its controls span all three pages." },
		{ 112, 112, 0, Family::ControlAll, "CTR-AL", "Control all", "Turns a parameter on all 16 tracks at once, and unlike FUNCTION + knob it can be sequenced." },
		{ 113, 113, 0, Family::Control8, "CTR-8P", "Control 8 parameters", "Collects 8 parameters from any tracks onto one page. Pick them on the EFFECTS and ROUTING pages." },
		{ 120, 120, 0, Family::ControlEcho, "CTR-RE", "Control Rhythm Echo", "Puts the master Rhythm Echo delay on the SYNTHESIS page, so it can be locked and sequenced. Its LFO controls are on ROUTING." },
		{ 121, 121, 0, Family::ControlReverb, "CTR-GB", "Control Gate Box", "Puts the master Gate Box reverb on the SYNTHESIS page, so it can be locked and sequenced. Its LFO controls are on ROUTING." },
		{ 122, 122, 0, Family::ControlEq, "CTR-EQ", "Control master EQ", "Puts the master EQ on the SYNTHESIS page, so it can be locked and sequenced. Its LFO controls are on ROUTING." },
		{ 123, 123, 0, Family::ControlDynamix, "CTR-DX", "Control Dynamix", "Puts the master Dynamix compressor on the SYNTHESIS page, so it can be locked and sequenced. Its LFO controls are on ROUTING." },
		{ 0x100, 0x117, 1, Family::Rom, "ROM-", "ROM sample", "Plays a user sample from ROM. Samples survive power-off." },
		{ 0x118, 0x11f, 25, Family::Rom, "ROM-", "ROM loop sample", "Plays a user sample from ROM, tuned for loops: HOLD reaches 2 bars, STRT and END are linear." },
		{ 0x120, 0x120, 0, Family::RamRecord, "RAM-R1", "RAM record 1", "Records the main outs or the inputs into RAM for RAM-P1 to play. Lost at power-off." },
		{ 0x121, 0x121, 0, Family::RamRecord, "RAM-R2", "RAM record 2", "Records the main outs or the inputs into RAM for RAM-P2 to play. Lost at power-off." },
		{ 0x122, 0x122, 0, Family::Rom, "RAM-P1", "RAM play 1", "Plays back what RAM-R1 recorded, like a loop ROM machine." },
		{ 0x123, 0x123, 0, Family::Rom, "RAM-P2", "RAM play 2", "Plays back what RAM-R2 recorded, like a loop ROM machine." },
		{ 0x125, 0x125, 0, Family::RamRecord, "RAM-R3", "RAM record 3", "Records the main outs or the inputs into RAM for RAM-P3 to play. Lost at power-off." },
		{ 0x126, 0x126, 0, Family::RamRecord, "RAM-R4", "RAM record 4", "Records the main outs or the inputs into RAM for RAM-P4 to play. Lost at power-off." },
		{ 0x127, 0x127, 0, Family::Rom, "RAM-P3", "RAM play 3", "Plays back what RAM-R3 recorded, like a loop ROM machine." },
		{ 0x128, 0x128, 0, Family::Rom, "RAM-P4", "RAM play 4", "Plays back what RAM-R4 recorded, like a loop ROM machine." },
		{ 0x130, 0x13f, 33, Family::Rom, "ROM-", "ROM loop sample", "Plays a user sample from ROM, tuned for loops: HOLD reaches 2 bars, STRT and END are linear." },
	};

	// TRACK EFFECTS and ROUTING, identical for every machine except MIDI and CTR machines.
	inline constexpr parameterHelp::Page g_effects
	{{
		{ "AMD",  "AM depth",              "Depth of the amplitude modulator, a volume LFO also known as tremolo." },
		{ "AMF",  "AM frequency",          "Speed of the amplitude modulator. It goes fast enough for extreme effects." },
		{ "EQF",  "EQ frequency",          "The centre frequency the track EQ boosts or cuts." },
		{ "EQG",  "EQ gain",               "Boost (positive) or cut (negative) around EQF." },
		{ "FLTF", "Filter base",           "Lower cutoff of the 24 dB filter. With FLTW at maximum it acts as a high-pass cutoff." },
		{ "FLTW", "Filter width",          "Gap between the high-pass and low-pass cutoffs. With FLTF at zero it acts as a low-pass cutoff." },
		{ "FLTQ", "Filter Q",              "How much the level is boosted around the filter cutoffs." },
		{ "SRR",  "Sample-rate reduction", "Lo-fi downsampling by sample and hold." },
	}};

	inline constexpr parameterHelp::Page g_routing
	{{
		{ "DIST", "Distortion",    "Overload distortion, after the track effects and before volume and pan." },
		{ "VOL",  "Volume",        "The track's volume. Unlike LEVEL, this one can be locked and modulated by LFOs." },
		{ "PAN",  "Pan",           "Position in the stereo field: -64 is hard left, +63 hard right. No effect on an individual output." },
		{ "DEL",  "Delay send",    "How much of the track goes to the Rhythm Echo delay." },
		{ "REV",  "Reverb send",   "How much of the track goes to the Gate Box reverb." },
		{ "LFOS", "LFO speed",     "Speed of this track's LFO, the same as SPEED in the LFO window." },
		{ "LFOD", "LFO depth",     "Depth of this track's LFO, the same as DEPTH in the LFO window." },
		{ "LFOM", "LFO shape mix", "Mix between the LFO's two waveforms, the same as SHMIX in the LFO window." },
	}};

	// The LFO window (FUNCTION + SYNTHESIS/EFFECTS/ROUTING).
	inline constexpr parameterHelp::Page g_lfo
	{{
		{ "TRACK", "Target track",     "Which track the LFO modulates, including tracks whose LFOs you want to modulate." },
		{ "PARAM", "Target parameter", "Which SYNTHESIS, EFFECTS or ROUTING parameter of that track is modulated." },
		{ "SHP1",  "Shape 1",          "Triangle, saw, square, linear decay, exponential decay or random." },
		{ "SHP2",  "Shape 2",          "Inverted versions of the SHP1 shapes." },
		{ "UPDTE", "Update",           "FREE never restarts, TRIG restarts on each trig, HOLD samples and holds on each trig." },
		{ "SPEED", "Speed",            "LFO rate relative to tempo, in 1/128 note steps." },
		{ "DEPTH", "Depth",            "How strongly the LFO moves the target parameter." },
		{ "SHMIX", "Shape mix",        "Balance between SHP1 (at zero) and SHP2 (at maximum)." },
	}};

	// Master effects in the KIT > MASTER FX window, in knob order. The CTR-RE/GB/EQ/DX machines
	// show the same labels on their SYNTHESIS page.
	inline constexpr const char* g_masterFxLabels[4][8] =
	{
		{ "TIME", "MOD", "MFRQ", "FB", "FLTF", "FLTW", "MONO", "LEV" },
		{ "DVOL", "PRED", "DEC", "DAMP", "HP", "LP", "GATE", "LEV" },
		{ "LF", "LG", "HF", "HG", "PF", "PG", "PQ", "GAIN" },
		{ "ATCK", "REL", "TRHD", "RTIO", "KNEE", "HP", "OUTG", "MIX" },
	};
	inline constexpr Family g_masterFxFamilies[4] = { Family::ControlEcho, Family::ControlReverb, Family::ControlEq, Family::ControlDynamix };
	inline constexpr const char* g_masterFxNames[4] = { "Rhythm Echo", "Gate Box reverb", "Master EQ", "Dynamix" };

	struct Parameter
	{
		Family family;
		const char* label;
		Entry entry;
	};

	inline constexpr Parameter g_parameters[] =
	{
		{ Family::Gnd, "PTCH", { "PTCH", "Pitch", "The basic pitch of the tone." } },
		{ Family::Gnd, "DEC",  { "DEC",  "Decay", "How long the sound takes to fade out." } },
		{ Family::Gnd, "RAMP", { "RAMP", "Pitch ramp", "How far the pitch sweeps at the start of the sound." } },
		{ Family::Gnd, "RDEC", { "RDEC", "Ramp decay", "How quickly the pitch ramp settles." } },
		{ Family::Gnd, "UP",   { "UP",   "Up time", "How long the impulse stays positive." } },
		{ Family::Gnd, "UVAL", { "UVAL", "Up value", "The level of the positive phase." } },
		{ Family::Gnd, "DOWN", { "DOWN", "Down time", "How long the impulse stays negative." } },
		{ Family::Gnd, "DVAL", { "DVAL", "Down value", "The level of the negative phase." } },

		{ Family::Trx, "PTCH", { "PTCH", "Pitch", "The basic pitch of the drum." } },
		{ Family::Trx, "DEC",  { "DEC",  "Decay", "How long the sound takes to fade out." } },
		{ Family::Trx, "RAMP", { "RAMP", "Pitch ramp", "Sweeps the pitch at the start of the sound." } },
		{ Family::Trx, "RDEC", { "RDEC", "Ramp decay", "How quickly the pitch ramp settles." } },
		{ Family::Trx, "STRT", { "STRT", "Start", "Makes the start of the sound harder." } },
		{ Family::Trx, "NOIS", { "NOIS", "Noise", "Adds noise to the start of the sound." } },
		{ Family::Trx, "HARM", { "HARM", "Harmonics", "Adds extra harmonics." } },
		{ Family::Trx, "CLIP", { "CLIP", "Clip", "A special type of distortion." } },
		{ Family::Trx, "BUMP", { "BUMP", "Bump", "Adds a pitch shift at the start of the sound." } },
		{ Family::Trx, "BENV", { "BENV", "Bump envelope", "How the bump fades out." } },
		{ Family::Trx, "SNAP", { "SNAP", "Snap", "The amount of snap at the start." } },
		{ Family::Trx, "TONE", { "TONE", "Tone", "Changes the tonal quality." } },
		{ Family::Trx, "TUNE", { "TUNE", "Tune", "Detunes the sound." } },
		{ Family::Trx, "DAMP", { "DAMP", "Damping", "Dampens the decay part of the sound." } },
		{ Family::Trx, "DIST", { "DIST", "Distortion", "A distortion built into the machine, separate from DIST on the ROUTING page." } },
		{ Family::Trx, "DTYP", { "DTYP", "Distortion type", "How hard the distortion is." } },
		{ Family::Trx, "CLPY", { "CLPY", "Clappiness", "Density of the clap." } },
		{ Family::Trx, "HARD", { "HARD", "Hardness", "Gives the sound a harder character." } },
		{ Family::Trx, "RICH", { "RICH", "Richness", "Enhances the richness of the sound." } },
		{ Family::Trx, "RATE", { "RATE", "Rate", "Rate of the individual claps." } },
		{ Family::Trx, "ROOM", { "ROOM", "Room", "Adds a room sound." } },
		{ Family::Trx, "RSIZ", { "RSIZ", "Room size", "The size of the room." } },
		{ Family::Trx, "RTUN", { "RTUN", "Room tune", "The tonal quality of the room." } },
		{ Family::Trx, "ENH",  { "ENH",  "Enhance", "Enhances the body of the sound." } },
		{ Family::Trx, "GAP",  { "GAP",  "Gap", "The gap between the two hi-hat cymbals." } },
		{ Family::Trx, "HPF",  { "HPF",  "High-pass filter", "High-pass filters the sound." } },
		{ Family::Trx, "LPF",  { "LPF",  "Low-pass filter", "Low-pass filters the sound." } },
		{ Family::Trx, "MTAL", { "MTAL", "Metal", "Adds extra metallic character." } },
		{ Family::Trx, "TOP",  { "TOP",  "Top", "Amount of high-frequency harmonics." } },
		{ Family::Trx, "TTUN", { "TTUN", "Top tune", "Tunes the high-frequency harmonics." } },
		{ Family::Trx, "SIZE", { "SIZE", "Size", "The size of the cymbal." } },
		{ Family::Trx, "PEAK", { "PEAK", "Peak", "Gives the sound more edge." } },
		{ Family::Trx, "ATT",  { "ATT",  "Attack", "Length of the attack." } },
		{ Family::Trx, "SUS",  { "SUS",  "Sustain", "Length of the sustain." } },
		{ Family::Trx, "REV",  { "REV",  "Reverse", "Reverses the movement of the maracas." } },
		{ Family::Trx, "RATL", { "RATL", "Rattle", "Adds extra rattle." } },
		{ Family::Trx, "RTYP", { "RTYP", "Rattle type", "The type of rattle." } },
		{ Family::Trx, "DUAL", { "DUAL", "Dual", "Introduces a double attack." } },
		{ Family::Trx, "CLIC", { "CLIC", "Click", "Adds a click at the start." } },
		{ Family::Trx, "HOLD", { "HOLD", "Hold", "How long the volume holds before it decays." } },
		{ Family::Trx, "TICK", { "TICK", "Tick", "Adds a tick to make the start harder." } },
		{ Family::Trx, "DIRT", { "DIRT", "Dirt", "Bit reduction for the bass drum." } },

		{ Family::Efm, "PTCH", { "PTCH", "Pitch", "The basic pitch of the drum." } },
		{ Family::Efm, "DEC",  { "DEC",  "Decay", "How long the sound takes to fade out." } },
		{ Family::Efm, "RAMP", { "RAMP", "Pitch ramp", "Depth of the pitch ramp at the start." } },
		{ Family::Efm, "RDEC", { "RDEC", "Ramp decay", "How long the pitch ramp takes to settle." } },
		{ Family::Efm, "MOD",  { "MOD",  "FM depth", "How much frequency modulation is applied." } },
		{ Family::Efm, "MFRQ", { "MFRQ", "Modulation frequency", "Frequency of the modulator." } },
		{ Family::Efm, "MDEC", { "MDEC", "Modulation decay", "How long the modulation takes to fade out." } },
		{ Family::Efm, "MFB",  { "MFB",  "Modulation feedback", "Feeds the modulator back into itself." } },
		{ Family::Efm, "NOIS", { "NOIS", "Noise", "The amount of noise in the snare." } },
		{ Family::Efm, "NDEC", { "NDEC", "Noise decay", "How long the noise takes to fade out." } },
		{ Family::Efm, "HPF",  { "HPF",  "High-pass filter", "High-pass filter frequency." } },
		{ Family::Efm, "CLIC", { "CLIC", "Click", "Adds a click to the start of the drum." } },
		{ Family::Efm, "CLPS", { "CLPS", "Claps", "The number of claps." } },
		{ Family::Efm, "CDEC", { "CDEC", "Clap decay", "How long the claps take to fade out." } },
		{ Family::Efm, "SNAR", { "SNAR", "Snare", "Adds snare drum timbre." } },
		{ Family::Efm, "SPTC", { "SPTC", "Snare pitch", "Pitch of the snare timbre." } },
		{ Family::Efm, "SDEC", { "SDEC", "Snare decay", "Decay of the snare timbre." } },
		{ Family::Efm, "SMOD", { "SMOD", "Snare modulation", "Modulation depth of the snare timbre." } },
		{ Family::Efm, "SNAP", { "SNAP", "Snap", "The amount of snap at the start." } },
		{ Family::Efm, "FB",   { "FB",   "Feedback", "Feedback amount." } },
		{ Family::Efm, "TREM", { "TREM", "Tremolo", "Depth of the tremolo." } },
		{ Family::Efm, "TFRQ", { "TFRQ", "Tremolo frequency", "Speed of the tremolo." } },

		{ Family::E12, "PTCH", { "PTCH", "Pitch", "The basic pitch of the sample." } },
		{ Family::E12, "DEC",  { "DEC",  "Decay", "How long the sound takes to fade out." } },
		{ Family::E12, "SNAP", { "SNAP", "Snap", "Depth of the snap, for a harsher attack." } },
		{ Family::E12, "SPLN", { "SPLN", "Snap length", "Length of the snap." } },
		{ Family::E12, "STRT", { "STRT", "Start", "Moves the start point of the sample forward." } },
		{ Family::E12, "RTRG", { "RTRG", "Retrigs", "How many times the sound retriggers." } },
		{ Family::E12, "RTIM", { "RTIM", "Retrig time", "Time between retrigs, relative to tempo." } },
		{ Family::E12, "BEND", { "BEND", "Pitch bend", "Bends the pitch up or down into the basic pitch." } },
		{ Family::E12, "HP",   { "HP",   "High-pass", "High-pass filter frequency." } },
		{ Family::E12, "HPQ",  { "HPQ",  "High-pass Q", "Resonance of the high-pass filter." } },
		{ Family::E12, "RING", { "RING", "Ring", "Adds ringing overtones." } },
		{ Family::E12, "RATL", { "RATL", "Rattle", "Adds ringing to the sound." } },
		{ Family::E12, "STOP", { "STOP", "Stop", "How long the sound plays before it is cut off abruptly." } },
		{ Family::E12, "BELL", { "BELL", "Bell", "Blends in the sound of the cymbal's inner bell." } },
		{ Family::E12, "REAL", { "REAL", "Realism", "Enhances the brush effect." } },
		{ Family::E12, "SLEW", { "SLEW", "Slew", "The effect of shaking back and forth." } },
		{ Family::E12, "BC",   { "BC",   "Bongo/conga", "Morphs between a bongo and a conga." } },

		{ Family::PhysicallyInformed, "PTCH", { "PTCH", "Pitch", "The basic pitch." } },
		{ Family::PhysicallyInformed, "DEC",  { "DEC",  "Decay", "How long the sound takes to fade out." } },
		{ Family::PhysicallyInformed, "HARD", { "HARD", "Hardness", "Higher values give a harder strike." } },
		{ Family::PhysicallyInformed, "HAMR", { "HAMR", "Hammer", "Higher values give a softer mallet." } },
		{ Family::PhysicallyInformed, "TENS", { "TENS", "Tension", "The effect of skin tension from a hard hit." } },
		{ Family::PhysicallyInformed, "DAMP", { "DAMP", "Damping", "Damping in the drum body." } },
		{ Family::PhysicallyInformed, "RING", { "RING", "Ring", "The amount of metallic ringing." } },
		{ Family::PhysicallyInformed, "RVOL", { "RVOL", "Rattle volume", "Volume of the snares' rattle." } },
		{ Family::PhysicallyInformed, "RDEC", { "RDEC", "Rattle decay", "Decay time of the rattle." } },
		{ Family::PhysicallyInformed, "TUNE", { "TUNE", "Tuning", "Emulates different tunings of the skins." } },
		{ Family::PhysicallyInformed, "SIZE", { "SIZE", "Size", "The size of the drum body or maraca." } },
		{ Family::PhysicallyInformed, "POS",  { "POS",  "Position", "Moves the striking point from the centre to the edge." } },
		{ Family::PhysicallyInformed, "GRNS", { "GRNS", "Grains", "The number of grains in the maraca." } },
		{ Family::PhysicallyInformed, "GLEN", { "GLEN", "Grain length", "Decay time of the individual grains." } },
		{ Family::PhysicallyInformed, "AG",   { "AG",   "AG", "Enhances the high frequencies." } },
		{ Family::PhysicallyInformed, "AU",   { "AU",   "AU", "Reduces the high frequencies." } },
		{ Family::PhysicallyInformed, "BR",   { "BR",   "BR", "Controls the low frequencies." } },
		{ Family::PhysicallyInformed, "GRAB", { "GRAB", "Grab", "Time until the cymbal is grabbed. 127 never grabs it." } },
		{ Family::PhysicallyInformed, "CLSN", { "CLSN", "Collision", "Slight contact between the two hi-hat cymbals." } },
		{ Family::PhysicallyInformed, "CLOS", { "CLOS", "Close", "Time until the hi-hat closes. 127 never closes it." } },

		{ Family::Input, "VOL",  { "VOL",  "Volume", "Input volume." } },
		{ Family::Input, "GATE", { "GATE", "Gate", "Gate sensitivity. Lower values let quieter signals through." } },
		{ Family::Input, "ATCK", { "ATCK", "Attack", "Gate attack time. Higher values open the gate more slowly." } },
		{ Family::Input, "HLD",  { "HLD",  "Hold", "How long the gate stays fully open after the input falls below the gate level." } },
		{ Family::Input, "DEC",  { "DEC",  "Decay", "Gate decay time after the hold phase." } },
		{ Family::Input, "ALEV", { "ALEV", "Input level", "Input volume." } },
		{ Family::Input, "FATK", { "FATK", "Filter attack", "Attack time of the filter gate. Higher values open it more slowly." } },
		{ Family::Input, "FHLD", { "FHLD", "Filter hold", "Hold time of the filter envelope." } },
		{ Family::Input, "FDEC", { "FDEC", "Filter decay", "Decay time of the filter envelope." } },
		{ Family::Input, "FDPH", { "FDPH", "Filter depth", "How far the envelope moves the filter cutoff." } },
		{ Family::Input, "FFRQ", { "FFRQ", "Filter frequency", "Base cutoff frequency of the input filter." } },
		{ Family::Input, "FQ",   { "FQ",   "Filter Q", "Resonance of the input filter." } },
		{ Family::Input, "AHLD", { "AHLD", "Amplitude hold", "Hold time of the input level. Higher values keep it open longer." } },
		{ Family::Input, "ADEC", { "ADEC", "Amplitude decay", "Decay time of the input level." } },

		{ Family::Midi, "NOTE", { "NOTE", "Note", "The MIDI note to play, C-2 to G8." } },
		{ Family::Midi, "N2",   { "N2",   "Chord note 2", "Adds a note this many semitones from NOTE. 0 is off." } },
		{ Family::Midi, "N3",   { "N3",   "Chord note 3", "Adds a note this many semitones from NOTE. 0 is off." } },
		{ Family::Midi, "LEN",  { "LEN",  "Length", "Length of the notes." } },
		{ Family::Midi, "VEL",  { "VEL",  "Velocity", "Velocity for NOTE, N2 and N3." } },
		{ Family::Midi, "PB",   { "PB",   "Pitch bend", "MIDI pitch bend." } },
		{ Family::Midi, "MW",   { "MW",   "Mod wheel", "MIDI modulation wheel." } },
		{ Family::Midi, "AT",   { "AT",   "Aftertouch", "MIDI channel aftertouch." } },
		{ Family::Midi, "CC1D", { "CC1D", "CC 1 number", "Which control change CC1V sends." } },
		{ Family::Midi, "CC1V", { "CC1V", "CC 1 value", "The value sent on the control change chosen by CC1D." } },
		{ Family::Midi, "CC2D", { "CC2D", "CC 2 number", "Which control change CC2V sends." } },
		{ Family::Midi, "CC2V", { "CC2V", "CC 2 value", "The value sent on the control change chosen by CC2D." } },
		{ Family::Midi, "CC3D", { "CC3D", "CC 3 number", "Which control change CC3V sends." } },
		{ Family::Midi, "CC3V", { "CC3V", "CC 3 value", "The value sent on the control change chosen by CC3D." } },
		{ Family::Midi, "CC4D", { "CC4D", "CC 4 number", "Which control change CC4V sends." } },
		{ Family::Midi, "CC4V", { "CC4V", "CC 4 value", "The value sent on the control change chosen by CC4D." } },
		{ Family::Midi, "CC5D", { "CC5D", "CC 5 number", "Which control change CC5V sends." } },
		{ Family::Midi, "CC5V", { "CC5V", "CC 5 value", "The value sent on the control change chosen by CC5D." } },
		{ Family::Midi, "CC6D", { "CC6D", "CC 6 number", "Which control change CC6V sends." } },
		{ Family::Midi, "CC6V", { "CC6V", "CC 6 value", "The value sent on the control change chosen by CC6D." } },
		{ Family::Midi, "PCHG", { "PCHG", "Program change", "Sends a program change, 0 to 126." } },

		{ Family::ControlAll, "[SYN1]", { "SYN1", "Synthesis 1, all tracks", "Turns SYNTHESIS parameter A on all 16 tracks at once." } },
		{ Family::ControlAll, "[SYN2]", { "SYN2", "Synthesis 2, all tracks", "Turns SYNTHESIS parameter B on all 16 tracks at once." } },
		{ Family::ControlAll, "[SYN3]", { "SYN3", "Synthesis 3, all tracks", "Turns SYNTHESIS parameter C on all 16 tracks at once." } },
		{ Family::ControlAll, "[SYN4]", { "SYN4", "Synthesis 4, all tracks", "Turns SYNTHESIS parameter D on all 16 tracks at once." } },
		{ Family::ControlAll, "[SYN5]", { "SYN5", "Synthesis 5, all tracks", "Turns SYNTHESIS parameter E on all 16 tracks at once." } },
		{ Family::ControlAll, "[SYN6]", { "SYN6", "Synthesis 6, all tracks", "Turns SYNTHESIS parameter F on all 16 tracks at once." } },
		{ Family::ControlAll, "[SYN7]", { "SYN7", "Synthesis 7, all tracks", "Turns SYNTHESIS parameter G on all 16 tracks at once." } },
		{ Family::ControlAll, "[SYN8]", { "SYN8", "Synthesis 8, all tracks", "Turns SYNTHESIS parameter H on all 16 tracks at once." } },

		{ Family::Control8, "P1", { "P1", "Shortcut 1", "Turns the parameter picked for shortcut 1 on the EFFECTS and ROUTING pages." } },
		{ Family::Control8, "P2", { "P2", "Shortcut 2", "Turns the parameter picked for shortcut 2 on the EFFECTS and ROUTING pages." } },
		{ Family::Control8, "P3", { "P3", "Shortcut 3", "Turns the parameter picked for shortcut 3 on the EFFECTS and ROUTING pages." } },
		{ Family::Control8, "P4", { "P4", "Shortcut 4", "Turns the parameter picked for shortcut 4 on the EFFECTS and ROUTING pages." } },
		{ Family::Control8, "P5", { "P5", "Shortcut 5", "Turns the parameter picked for shortcut 5 on the EFFECTS and ROUTING pages." } },
		{ Family::Control8, "P6", { "P6", "Shortcut 6", "Turns the parameter picked for shortcut 6 on the EFFECTS and ROUTING pages." } },
		{ Family::Control8, "P7", { "P7", "Shortcut 7", "Turns the parameter picked for shortcut 7 on the EFFECTS and ROUTING pages." } },
		{ Family::Control8, "P8", { "P8", "Shortcut 8", "Turns the parameter picked for shortcut 8 on the EFFECTS and ROUTING pages." } },

		{ Family::ControlEcho, "TIME", { "TIME", "Delay time", "Delay time relative to tempo, in 128th notes. 64 is two beats." } },
		{ Family::ControlEcho, "MOD",  { "MOD",  "Time modulation", "Depth of the delay time modulation." } },
		{ Family::ControlEcho, "MFRQ", { "MFRQ", "Modulation speed", "Frequency of the delay time modulation." } },
		{ Family::ControlEcho, "FB",   { "FB",   "Feedback", "Delay feedback, taken after the filter. Centred with the filter open gives unity feedback." } },
		{ Family::ControlEcho, "FLTF", { "FLTF", "Filter base", "Base frequency of the delay's filter." } },
		{ Family::ControlEcho, "FLTW", { "FLTW", "Filter width", "Width of the delay's filter." } },
		{ Family::ControlEcho, "MONO", { "MONO", "Feedback panning", "Low values ping-pong, high values keep the stereo image, the centre sits in the middle." } },
		{ Family::ControlEcho, "LEV",  { "LEV",  "Level", "Output level of the Rhythm Echo." } },

		{ Family::ControlReverb, "DVOL", { "DVOL", "Delay to reverb", "Sends the Rhythm Echo's output into the reverb." } },
		{ Family::ControlReverb, "PRED", { "PRED", "Pre-delay", "Delays the reverb, so it arrives after the sound." } },
		{ Family::ControlReverb, "DEC",  { "DEC",  "Decay", "How long the reverb takes to die out, 0.5 to 3 seconds." } },
		{ Family::ControlReverb, "DAMP", { "DAMP", "Damping", "Reduces high frequencies, like softer walls." } },
		{ Family::ControlReverb, "HP",   { "HP",   "High-pass", "High-pass filter on the reverb output." } },
		{ Family::ControlReverb, "LP",   { "LP",   "Low-pass", "Low-pass filter on the reverb output." } },
		{ Family::ControlReverb, "GATE", { "GATE", "Gate time", "Cuts the reverb after this time if the level is low. Maximum turns the gate off." } },
		{ Family::ControlReverb, "LEV",  { "LEV",  "Level", "Output level of the Gate Box reverb." } },

		{ Family::ControlEq, "LF",   { "LF",   "Low shelf frequency", "Cut/boost frequency of the low shelf." } },
		{ Family::ControlEq, "LG",   { "LG",   "Low shelf gain", "Boost or cut of the low frequencies, -15 to +15 dB." } },
		{ Family::ControlEq, "HF",   { "HF",   "High shelf frequency", "Cut/boost frequency of the high shelf." } },
		{ Family::ControlEq, "HG",   { "HG",   "High shelf gain", "Boost or cut of the high frequencies, -15 to +15 dB." } },
		{ Family::ControlEq, "PF",   { "PF",   "Parametric frequency", "Centre frequency of the parametric band." } },
		{ Family::ControlEq, "PG",   { "PG",   "Parametric gain", "Boost or cut at PF, -15 to +15 dB." } },
		{ Family::ControlEq, "PQ",   { "PQ",   "Parametric Q", "Width of the parametric band. Higher values are narrower." } },
		{ Family::ControlEq, "GAIN", { "GAIN", "Gain", "Final volume of the main stereo out." } },

		{ Family::ControlDynamix, "ATCK", { "ATCK", "Attack", "How fast the compressor reacts. Long attacks let transients through." } },
		{ Family::ControlDynamix, "REL",  { "REL",  "Release", "How fast it lets go. Long releases lift decaying sounds and flatten dynamics." } },
		{ Family::ControlDynamix, "TRHD", { "TRHD", "Threshold", "Level where compression starts, -48 to 0 dB." } },
		{ Family::ControlDynamix, "RTIO", { "RTIO", "Ratio", "How hard the signal is compressed, 1:1 to 1:256." } },
		{ Family::ControlDynamix, "KNEE", { "KNEE", "Knee", "Softens the transition into compression. Low values give a hard knee." } },
		{ Family::ControlDynamix, "HP",   { "HP",   "Sidechain high-pass", "Keeps bass from driving the compressor." } },
		{ Family::ControlDynamix, "OUTG", { "OUTG", "Output gain", "Makes up the level lost to compression." } },
		{ Family::ControlDynamix, "MIX",  { "MIX",  "Mix", "Blend of compressed and original signal. High values bypass Dynamix." } },

		{ Family::Rom, "PTCH", { "PTCH", "Pitch", "Two octaves up or down. In the first octave every third step is a semitone." } },
		{ Family::Rom, "DEC",  { "DEC",  "Decay", "Decay time. On a looped sample 127 loops forever." } },
		{ Family::Rom, "HOLD", { "HOLD", "Hold", "How long the amp envelope stays open: 127 is 1 bar, or 2 bars on loop machines." } },
		{ Family::Rom, "BRR",  { "BRR",  "Bit rate reduction", "Lowers the bit depth. 127 is 2-bit." } },
		{ Family::Rom, "STRT", { "STRT", "Start", "Start point of the sample. Linear on loop machines: 16 steps per beat in a 2-bar loop." } },
		{ Family::Rom, "END",  { "END",  "End", "End point of the sample. Below STRT the sample plays reversed." } },
		{ Family::Rom, "RTRG", { "RTRG", "Retrigs", "How many times the sample retriggers. 127 retriggers forever." } },
		{ Family::Rom, "RTIM", { "RTIM", "Retrig time", "Time between retrigs, relative to tempo. 0 turns RTRG off." } },

		{ Family::RamRecord, "MLEV", { "MLEV", "Main level", "Level of the main outs in the recording. 0 records them as is." } },
		{ Family::RamRecord, "MBAL", { "MBAL", "Main balance", "Balance of the main outs in the mono recording." } },
		{ Family::RamRecord, "ILEV", { "ILEV", "Input level", "Level of the external inputs in the recording. 0 records them as is." } },
		{ Family::RamRecord, "IBAL", { "IBAL", "Input balance", "Balance of the external inputs in the mono recording." } },
		{ Family::RamRecord, "CUE1", { "CUE1", "Cue 1", "Pre-listen level of the main outs or inputs. Careful: it can feed back." } },
		{ Family::RamRecord, "CUE2", { "CUE2", "Cue 2", "Pre-listen level of what will be recorded when the machine is trigged." } },
		{ Family::RamRecord, "LEN",  { "LEN",  "Length", "Recording length in quarter steps. 127 records 2 bars." } },
		{ Family::RamRecord, "RATE", { "RATE", "Rate", "Recording quality. Lower values save DSP memory." } },
	};

	// The LFO window prints these as text. Captured with mdmmLcdCapture (mode "md mdlfo").
	inline constexpr parameterHelp::ValueHash g_lfoUpdateValues[] =
	{
		{ 0x0f1ff25dbbca3ab3ull, "FREE", "Never restarts: the LFO keeps running whatever you play." },
		{ 0x977bd6602bcbae6full, "TRIG", "Restarts every time the target track is trigged." },
		{ 0x88f5b25fa5281107ull, "HOLD", "Samples and holds: each trig freezes the LFO's level until the next one." },
	};
	inline const parameterHelp::ValueHash* lfoUpdateForHash(const uint64_t _hash)
	{
		return parameterHelp::findByHash(g_lfoUpdateValues, _hash);
	}
	inline const char* labelForHash(const uint64_t _hash)
	{
		return parameterHelp::labelForHash(g_labelHashes, _hash);
	}

	// The machine and its key, or nullptr.
	inline const Machine* machineForHash(const uint64_t _hash, uint16_t& _key)
	{
		for(const auto& entry : g_machineHashes)
		{
			if(entry.hash != _hash)
				continue;
			for(const auto& machine : g_machines)
			{
				if(entry.key >= machine.first && entry.key <= machine.last)
				{
					_key = entry.key;
					return &machine;
				}
			}
		}
		return nullptr;
	}

	inline const Entry* parameter(const Family _family, const char* _label)
	{
		for(const auto& p : g_parameters)
			if(p.family == _family && std::strcmp(p.label, _label) == 0)
				return &p.entry;
		return nullptr;
	}

	// _page follows the LEDs: 0 SYNTHESIS, 1 EFFECTS, 2 ROUTING. _machine may be null (unknown).
	// _allTracks is set for CTR-AL's inverted copies of the EFFECTS/ROUTING labels.
	inline const Entry* entry(const int _page, const Machine* _machine, const char* _label, bool& _allTracks)
	{
		_allTracks = false;
		if(!_label || _page < 0 || _page > 2)
			return nullptr;
		if(_page > 0)
		{
			const auto& page = _page == 1 ? g_effects : g_routing;
			if(const auto* const fixed = parameterHelp::entryForLabel(page, _label))
				return fixed;
			if(_machine && _machine->family == Family::ControlAll && _label[0] == '[')
			{
				const std::string inner(_label + 1, std::strlen(_label) - 2);
				if(const auto* const fixed = parameterHelp::entryForLabel(page, inner.c_str()))
				{
					_allTracks = true;
					return fixed;
				}
			}
			// MIDI machines use these pages for more MIDI controls.
			return _machine && _machine->family == Family::Midi ? parameter(_machine->family, _label) : nullptr;
		}
		return _machine ? parameter(_machine->family, _label) : nullptr;
	}
}
