#pragma once

#include <cstdint>
#include <cstring>
#include <iterator>

#include "mdParameterHelp.h"

// Plain-language help for Monomachine machines and their SYNTHESIS page parameters.
// The LCD is identified through lcdText hashes; descriptions are paraphrased from the
// machine reference (Appendix A) of the owner's manual.
namespace mdJucePlugin::monomachineHelp
{
	using parameterHelp::LabelHash;
	using parameterHelp::ValueHash;

	struct MachineHash
	{
		uint64_t hash;
		uint8_t machine;
	};

	// Generated by mdmmLcdCapture from Monomachine OS 1.32b screens (fields and machine name).
	inline constexpr LabelHash g_labelHashes[] =
	{
		{ 0xbdc8e334eac08170ull, "TUNE" }, { 0x557f740d73ee4f6bull, "ST" }, { 0x85e106677c005ecdull, "RED" },
		{ 0xf239af8ed016c3ddull, "STON" }, { 0x0d044edfe44d2936ull, "PW" }, { 0xd3893cb53a187462ull, "PWAD" },
		{ 0x8d9bf082cbefc220ull, "PWRS" }, { 0xa861ae62fa5d0db3ull, "WAVE" }, { 0x265710f6fa141854ull, "MOD" },
		{ 0xda1978298fb239b9ull, "MSRC" }, { 0x6be3e7ddf7b4731bull, "MFRQ" }, { 0xe3abf15220931f98ull, "UNIL" },
		{ 0xdc0ec074893582ceull, "UNIW" }, { 0xb1892d45067f970cull, "UNIX" }, { 0xeba77c162099a090ull, "SUBX" },
		{ 0xb254f0e77c41b33full, "SUB1" }, { 0x80923326fb992cfcull, "SUB2" }, { 0xd4e3e2d42780fccaull, "WP" },
		{ 0xe0ef19296bda49b9ull, "WPM" }, { 0xab65ed0061c3f874ull, "WPRS" }, { 0x35b0eeb7f110332eull, "SYNC" },
		{ 0xb4119762f03e5b61ull, "SFRQ" }, { 0x0754f86a8c1c8fd2ull, "PTCH" }, { 0xdb242ebf52961051ull, "STRT" },
		{ 0x03d83be16a76271full, "RTRG" }, { 0x1749ef3d87c1eeefull, "RTIM" }, { 0x24ce75f1bd3367ceull, "1FRQ" },
		{ 0x7b62df16d8308ba1ull, "1FIN" }, { 0x22ff5f708e8ba170ull, "1ENV" }, { 0x22b943d846981174ull, "1FB" },
		{ 0x9e5bf5401702c989ull, "2FRQ" }, { 0xf9faa6193db0bf99ull, "2VOL" }, { 0xa7b9c87af080f01dull, "TONE" },
		{ 0xc25f31a93342d51bull, "2ENV" }, { 0x3635910b5f86437dull, "3FRQ" }, { 0x5a38cd747bc64f0full, "3ENV" },
		{ 0x922e00e5e2a78f65ull, "1FEN" }, { 0xae386f064c61929eull, "1VOL" }, { 0xf80f0998be537894ull, "1VEN" },
		{ 0xa2210bf975406c43ull, "2FB" }, { 0x34c04b9bf51cf260ull, "VOC1" }, { 0x66a2f82a5be69c9full, "VOC2" },
		{ 0x82db12e14a3ee126ull, "V-SW" }, { 0x63276c186d655597ull, "VOIC" }, { 0x55e95647fd7a7c73ull, "CONS" },
		{ 0x7dfd759fa6d8285aull, "CLEN" }, { 0xc99cbe2755f32327ull, "CVOL" }, { 0x03fa7997ff37abb2ull, "INP" },
		{ 0x51544a2772d4d181ull, "DEC" }, { 0x6848e1c0a70d8dc2ull, "DAMP" }, { 0x460e748608d2a1f6ull, "GATE" },
		{ 0x73f723acbd98505cull, "MIX" }, { 0x018c2fc07563c8c8ull, "HP" }, { 0x36b15b9b81333f1cull, "LP" },
		{ 0x3c1405761465753aull, "PCH2" }, { 0x6e5678a1de689f06ull, "PCH3" }, { 0x38815b25a6e90920ull, "PCH4" },
		{ 0xf496117c2ce1c167ull, "CHRL" }, { 0xed8047cfe65fbd09ull, "CHRW" }, { 0x67cfbd98365cd057ull, "DEL" },
		{ 0xa2b35e482f89e9a8ull, "DEP" }, { 0x3e19608ea9f6ab68ull, "SPD" }, { 0x0ae5aaf3b2113cf6ull, "FB" },
		{ 0x673ad2cc83baab09ull, "WID" }, { 0x111b198cf048c120ull, "ATK" }, { 0xd2dc26f80c5f3fc0ull, "REL" },
		{ 0x01e177e006c0f46dull, "THRS" }, { 0xcfe3e966689a2f49ull, "RAT" }, { 0xb5df391876875361ull, "GAIN" },
		{ 0xde6be76c1f801662ull, "RMS" }, { 0x6e556dc4ffab4c9aull, "EXT" }, { 0x64bb8154a7d52bf0ull, "CNTR" },
		{ 0x0aa57a8e71394530ull, "WAV1" }, { 0x03aea0be282b3e8full, "WAV2" }, { 0xdff3386ca5d5b8f9ull, "TIME" },
		{ 0xefb6107cac03ab58ull, "BR1" }, { 0xe903489ad0926a37ull, "BR2" },
		// Fixed DATA pages (AMP, FILTER, EFFECTS, LFO).
		{ 0xa68751bc2df4b213ull, "HOLD" }, { 0x6d14b010248e0ddeull, "DIST" }, { 0xab66dfe3beead810ull, "VOL" },
		{ 0x933f19f8fde27cf3ull, "PAN" }, { 0x5a7bc6533a48b68bull, "PORT" }, { 0x5390bf88c2f0eee9ull, "BASE" },
		{ 0x91ca927df9e27bf4ull, "WDTH" }, { 0xe0004fce56a4a9fbull, "HPQ" }, { 0xaf873b717914e63bull, "LPQ" },
		{ 0x6d026202653a5cf3ull, "BOFS" }, { 0x4847ba680b49e902ull, "WOFS" }, { 0xb021c5d20d73328eull, "EQF" },
		{ 0x3c5225a461492978ull, "EQG" }, { 0x7974386e85ff4d06ull, "SRR" }, { 0x4590927375dcb0a4ull, "DTIM" },
		{ 0xb4649de6a311d230ull, "DSND" }, { 0x576db990976889e2ull, "DFB" }, { 0xd729d7ea371f7614ull, "DBAS" },
		{ 0xa8cee5e53ccf1f15ull, "DWID" }, { 0xc7042938313012fdull, "PAGE" }, { 0xb9dce5aa25fd9c22ull, "DEST" },
		{ 0x01dc17f9cdc8c639ull, "TRIG" }, { 0xc455226ad5749c79ull, "MULT" }, { 0x7fb870599b2d8d40ull, "INTL" },
		{ 0xace8d68a0f644cddull, "DPTH" },
	};

	// LFO PAGE values: the page an LFO targets. dataPage follows the DATA PAGE LEDs, -1 if none.
	struct LfoPage
	{
		uint64_t hash;
		const char* text;
		const char* name;
		int dataPage;
	};

	inline constexpr LfoPage g_lfoPages[] =
	{
		{ 0x0754f86a8c1c8fd2ull, "PTCH", "Pitch", -1 },
		{ 0x4fbd351e744e46e4ull, "SYNT", "Synthesis", 0 },
		{ 0x8223321acd562ab6ull, "AMP", "Amplification", 1 },
		{ 0x658a08ceeec90b69ull, "FILT", "Filter", 2 },
		{ 0x601418be937d8ecfull, "EFFX", "Effects", 3 },
		{ 0xb474c0af472198bbull, "LFO1", "LFO 1", 4 },
		{ 0xfd1894940dcb42b8ull, "LFO2", "LFO 2", 5 },
		{ 0xd3dfe2f506d4fc74ull, "LFO3", "LFO 3", 6 },
		{ 0x9304ec2b9e6d8004ull, "MIDI", "MIDI sequencer", -1 },
	};

	// LFO DEST values that are not also DATA page labels: pitch ranges, MIDI sequencer
	// parameters, and the empty slot.
	inline constexpr parameterHelp::Entry g_lfoSpecialDestinations[] =
	{
		{ "1/12", "Pitch, 1 semitone", "Modulates pitch over a range of one semitone. Good for subtle vibrato." },
		{ "2/12", "Pitch, 2 semitones", "Modulates pitch over a range of two semitones." },
		{ "7/12", "Pitch, a fifth", "Modulates pitch over a range of seven semitones." },
		{ "1OCT", "Pitch, 1 octave", "Modulates pitch over a range of one octave." },
		{ "2OCT", "Pitch, 2 octaves", "Modulates pitch over a range of two octaves." },
		{ "4OCT", "Pitch, 4 octaves", "Modulates pitch over a range of four octaves." },
		{ "8OCT", "Pitch, 8 octaves", "Modulates pitch over a range of eight octaves." },
		{ "16OCT", "Pitch, 16 octaves", "Modulates pitch over sixteen octaves, for full-range sweeps." },
		{ "LEN", "MIDI note length", "The longest a MIDI note plays before its NOTE OFF." },
		{ "VEL", "MIDI velocity", "The velocity sent with each MIDI note." },
		{ "PB", "MIDI pitch bend", "The MIDI pitch bend value." },
		{ "PCHG", "MIDI program change", "Program changes sent to the external device. Only transmits when locked." },
		{ "CC 1", "MIDI CC 1", "Control change 1. Which CC it is is set in GLOBAL > MIDI SEQUENCER SETTINGS." },
		{ "CC 2", "MIDI CC 2", "Control change 2. Which CC it is is set in GLOBAL > MIDI SEQUENCER SETTINGS." },
		{ "CC 3", "MIDI CC 3", "Control change 3. Which CC it is is set in GLOBAL > MIDI SEQUENCER SETTINGS." },
		{ "CC 4", "MIDI CC 4", "Control change 4. Which CC it is is set in GLOBAL > MIDI SEQUENCER SETTINGS." },
		{ "---", "Nothing", "This destination slot is empty on the selected page." },
	};

	inline constexpr LabelHash g_lfoSpecialDestinationHashes[] =
	{
		{ 0x9e120c412a912f27ull, "1/12" }, { 0xdbd75665268c05a4ull, "2/12" }, { 0xbf00b425c51f1d8cull, "7/12" },
		{ 0xf05cfe38552efdbfull, "1OCT" }, { 0x67b063d6b28028c0ull, "2OCT" }, { 0x45e2fed59c57a60aull, "4OCT" },
		{ 0x054ac45809952d30ull, "8OCT" }, { 0x3798766eac82c5beull, "16OCT" }, { 0xe727c317ea322ea1ull, "LEN" },
		{ 0x35b4a81d8da28b29ull, "VEL" }, { 0x194645552ef42587ull, "PB" }, { 0xaad9ed30add993eaull, "PCHG" },
		{ 0xdd35063091869a99ull, "CC 1" }, { 0xa6bf1c3d96ad1a1cull, "CC 2" }, { 0xa85b31766b267fa8ull, "CC 3" },
		{ 0x5e641257be2fc092ull, "CC 4" }, { 0x2bdf879307d7e322ull, "---" },
	};

	inline constexpr MachineHash g_machineHashes[] =
	{
		{ 0xc5fda2cedc059202ull, 0 }, { 0x997386c02b1d12a5ull, 1 }, { 0x95006be1b1172c75ull, 2 },
		{ 0x0786fe3db5edc4f2ull, 3 }, { 0xe3f4f93a00dde299ull, 4 }, { 0xe2a0b32354f5ab80ull, 5 },
		{ 0x31e8c4622f79f9a3ull, 6 }, { 0xed2c53796197bf20ull, 7 }, { 0xf7c366db82434b9cull, 8 },
		{ 0x1ba756558c0ef99aull, 9 }, { 0x608a1b8aa6f0d600ull, 10 }, { 0xebbb5fa83e542e91ull, 11 },
		{ 0x63a5a4c7dfbac9feull, 12 }, { 0x416951c0f024b3c0ull, 13 }, { 0x913e00b73e8bfc93ull, 14 },
		{ 0x9daeb801c38d5ab9ull, 15 }, { 0x4a26fb964c48659cull, 16 }, { 0x62d78ba40d5ae5eaull, 17 },
		{ 0x223ac7e7881eae7eull, 18 }, { 0x2e436adc26c1f18dull, 19 }, { 0xa3fc1ff15abaf2f7ull, 32 },
		{ 0x85b6aa1b84672f4full, 33 },
	};

	struct Machine
	{
		uint8_t id;
		const char* lcdName;
		const char* name;
		const char* description;
	};

	inline constexpr Machine g_machines[] =
	{
		{ 0, "GND-GND", "Ground", "Makes no sound at all." },
		{ 1, "GND-SIN", "Sine wave", "A plain sine oscillator. A cleared track reverts to this." },
		{ 2, "GND-NOIS", "Noise", "A noise generator, from white through pink to red." },
		{ 3, "SID-6581", "SID 6581", "One oscillator modelled on the Commodore 64's MOS 6581 chip, with ring modulation and sync." },
		{ 4, "SWAVE-SAW", "SuperWave Saw", "Up to eight analogue-style sawtooth oscillators: a base oscillator plus unison and sub oscillators." },
		{ 5, "SWAVE-PULS", "SuperWave Pulse", "Five analogue-style pulse oscillators, three of them with pulse width modulation." },
		{ 6, "DPRO-WAVE", "DigiPRO Wave", "Crunchy 12-bit single-cycle waveforms that can morph and hard-sync. Pairs well with a filter." },
		{ 7, "DPRO-BBOX", "DigiPRO BeatBox", "24 percussive 12-bit samples spread across the keys, in the style of the Machinedrum's E12 sounds." },
		{ 8, "FM+STAT", "FM+ Static", "The most versatile FM+ machine: two FM modulators with frequencies picked from a list." },
		{ 9, "FM+PAR", "FM+ Parallel", "Three parallel copies of the FM+ block, each with its own frequency and envelope." },
		{ 10, "FM+DYN", "FM+ Dynamic", "The wildest FM+ machine: continuously variable frequencies with their own envelopes." },
		{ 11, "VO-VO-6", "VO-6 voice", "Formant voice synthesis. Each trig speaks an optional consonant followed by a vowel." },
		{ 12, "FX-THRU", "FX Thru", "Passes incoming audio through the track effects without processing it." },
		{ 13, "FX-REVERB", "FX Reverb", "A gated reverb, a version of the Elektron gate reverb from the Machinedrum." },
		{ 14, "SWAVE-ENS", "SuperWave Ensemble", "Up to eight sawtooth-based oscillators arranged into chords of up to four notes." },
		{ 15, "FX-CHORUS", "FX Chorus", "A stereo chorus with two sets of three delay taps." },
		{ 16, "FX-DYNAMIX", "FX Dynamix", "A compressor and limiter for raising level or shaping transients." },
		{ 17, "FX-RINGMOD", "FX Ring modulator", "Ring-modulates incoming audio against an internal carrier oscillator." },
		{ 18, "FX-PHASER", "FX Phaser", "A sweeping phase effect. It can also make a sound wider." },
		{ 19, "FX-FLANGER", "FX Flanger", "A flanger, with its notches spread evenly across the frequency range." },
		{ 32, "DPRO-DDRW", "DigiPRO DoubleDraw", "Builds an oscillator from two waveforms, with a glide between waveform changes and bit reduction. MKII only." },
		{ 33, "DPRO-DENS", "DigiPRO Ensemble", "Chords of up to four notes from a single DigiPRO waveform. MKII only." },
	};

	struct Parameter
	{
		uint8_t machine;
		const char* label;
		parameterHelp::Entry entry;
	};

	namespace text
	{
		inline constexpr const char* tune = "Sets the tuning of the oscillator.";
		inline constexpr const char* input = "Amplifies the incoming audio signal.";
		inline constexpr const char* mix = "Balance between the original (dry) signal and the processed (wet) signal.";
		inline constexpr const char* pitchOffset = "Adds a chord note this many semitones above the played note, or OFF. PCH2=4, PCH3=7 gives a major triad. The ratios 6/5, 5/4, 4/3 and 3/2 give just-intonation thirds, fourths and fifths: purer, beatless chords.";
	}

	inline constexpr Parameter g_parameters[] =
	{
		// GND-SIN, GND-NOIS
		{ 1, "TUNE", { "TUNE", "Tune", text::tune } },
		{ 2, "ST", { "ST", "Stereo", "Changes the character of the noise. With STON on, it widens the noise in stereo instead." } },
		{ 2, "RED", { "RED", "Redness", "Noise colour: 0 is white, 64 pink, maximum red." } },
		{ 2, "STON", { "STON", "Stereo on", "Makes ST control stereo width." } },
		{ 2, "TUNE", { "TUNE", "Tune", text::tune } },

		// SID-6581
		{ 3, "PW", { "PW", "Pulse width", "Shapes the PULSE waveform, and to some degree the MIXED one." } },
		{ 3, "PWAD", { "PWAD", "Pulse width add", "Depth of the pulse width sweep. 0 turns the sweep off." } },
		{ 3, "PWRS", { "PWRS", "Pulse width restart", "When on, each note restarts the pulse sweep from the PW position." } },
		{ 3, "WAVE", { "WAVE", "Waveform", "Triangle, saw, pulse, mixed (a digital SID wave) or noise." } },
		{ 3, "MOD", { "MOD", "Modulation", "Off, ring modulation, hard sync, or both." } },
		{ 3, "MSRC", { "MSRC", "Modulation source", "Where the second frequency comes from: MFRQ, or PRCH (the note on the previous track)." } },
		{ 3, "MFRQ", { "MFRQ", "Modulation frequency", "The modulating frequency when MSRC is set to MFRQ." } },
		{ 3, "TUNE", { "TUNE", "Tune", text::tune } },

		// SWAVE-SAW
		{ 4, "UNIL", { "UNIL", "Unison level", "Level of the unison saw pair above and below the base pitch." } },
		{ 4, "UNIW", { "UNIW", "Unison width", "How far the unison oscillators sit from the base pitch." } },
		{ 4, "UNIX", { "UNIX", "Extended unison level", "Level of a second unison pair at twice the UNIW distance. Needs UNIL above zero." } },
		{ 4, "SUBX", { "SUBX", "Square sub oscillator", "A square wave one octave below the base pitch." } },
		{ 4, "SUB1", { "SUB1", "Sub oscillator 1", "A sine one octave below the base pitch." } },
		{ 4, "SUB2", { "SUB2", "Sub oscillator 2", "A sine two octaves below the base pitch." } },
		{ 4, "TUNE", { "TUNE", "Tune", text::tune } },

		// SWAVE-PULS
		{ 5, "UNIL", { "UNIL", "Unison level", "Level of the unison pulse pair above and below the base pitch." } },
		{ 5, "UNIW", { "UNIW", "Unison width", "How far the unison oscillators sit from the base pitch." } },
		{ 5, "SUB1", { "SUB1", "Sub oscillator 1", "A sine one octave below the base pitch." } },
		{ 5, "SUB2", { "SUB2", "Sub oscillator 2", "A sine two octaves below the base pitch." } },
		{ 5, "PW", { "PW", "Pulse width", "Pulse width of the base and unison oscillators. Centre is square, either end moves toward a spike." } },
		{ 5, "PWAD", { "PWAD", "Pulse width add", "Speed of the sweep between square and spike. 0 turns the sweep off." } },
		{ 5, "PWRS", { "PWRS", "Pulse width restart", "When on, each note restarts the pulse sweep from the PW position." } },
		{ 5, "TUNE", { "TUNE", "Tune", text::tune } },

		// DPRO-WAVE
		{ 6, "WAVE", { "WAVE", "Waveform", "Picks one of 32 original 12-bit waveforms." } },
		{ 6, "WP", { "WP", "Wave phase", "Morphs the selected waveform toward the next one, in 128 steps." } },
		{ 6, "WPM", { "WPM", "Wave phase modulation", "Continuously sweeps the wave phase. 0 is off, higher is faster." } },
		{ 6, "WPRS", { "WPRS", "Wave phase restart", "When on, each note restarts the WPM sweep from the WP position." } },
		{ 6, "SYNC", { "SYNC", "Hard sync", "Off, sync to SFRQ, or sync to the note on the previous track (PRCH)." } },
		{ 6, "SFRQ", { "SFRQ", "Sync frequency", "The frequency the oscillator hard-syncs to when SYNC is set to SFRQ." } },
		{ 6, "TUNE", { "TUNE", "Tune", text::tune } },

		// DPRO-BBOX
		{ 7, "PTCH", { "PTCH", "Pitch", "Coarse pitch for all of the percussion sounds." } },
		{ 7, "STRT", { "STRT", "Sample start", "Where playback starts in the sample. 127 starts halfway through." } },
		{ 7, "RTRG", { "RTRG", "Retrig", "How many times the sample restarts. 0 is off, 127 retriggers forever." } },
		{ 7, "RTIM", { "RTIM", "Retrig time", "Time between retrigs. Very low values turn the retrigs into a pitch." } },

		// FM+STAT
		{ 8, "1FRQ", { "1FRQ", "Modulator 1 frequency", "Coarse frequency of modulator 1, from a list of FM-friendly ratios." } },
		{ 8, "1FIN", { "1FIN", "Modulator 1 fine tune", "Fine adjustment of modulator 1's frequency." } },
		{ 8, "1ENV", { "1ENV", "Modulator 1 level & envelope", "Output level of the first FM block, as a combined level and envelope: 0 to 64 is a steady level (64 = full). Above 64 it starts at full and decays on every note, faster towards 127." } },
		{ 8, "1FB", { "1FB", "Modulator 1 feedback", "Feedback of modulator 1." } },
		{ 8, "2FRQ", { "2FRQ", "Modulator 2 frequency", "Frequency of modulator 2, from the listed ratios." } },
		{ 8, "2VOL", { "2VOL", "Modulator 2 level & feedback", "Output level of the second FM block. High values add feedback for a stronger effect." } },
		{ 8, "TONE", { "TONE", "Tone", "Overall brightness of the FM sound. Higher adds more high harmonics." } },
		{ 8, "TUNE", { "TUNE", "Tune", "Sets the tuning of the output." } },

		// FM+PAR
		{ 9, "1FRQ", { "1FRQ", "Modulator 1 frequency", "Frequency of modulator 1, from the listed ratios." } },
		{ 9, "1ENV", { "1ENV", "Modulator 1 level & envelope", "Output level of FM block 1, as a combined level and envelope: 0 to 64 is a steady level (64 = full). Above 64 it starts at full and decays on every note, faster towards 127." } },
		{ 9, "2FRQ", { "2FRQ", "Modulator 2 frequency", "Frequency of modulator 2, from the listed ratios." } },
		{ 9, "2ENV", { "2ENV", "Modulator 2 level & envelope", "Output level of FM block 2, as a combined level and envelope: 0 to 64 is a steady level (64 = full). Above 64 it starts at full and decays on every note, faster towards 127." } },
		{ 9, "3FRQ", { "3FRQ", "Modulator 3 frequency", "Frequency of modulator 3, from the listed ratios." } },
		{ 9, "3ENV", { "3ENV", "Modulator 3 level & envelope", "Output level of FM block 3, as a combined level and envelope: 0 to 64 is a steady level (64 = full). Above 64 it starts at full and decays on every note, faster towards 127." } },
		{ 9, "TONE", { "TONE", "Tone", "Overall brightness of the FM sound. Higher adds more high harmonics." } },
		{ 9, "TUNE", { "TUNE", "Tune", "Sets the tuning of the output." } },

		// FM+DYN
		{ 10, "1FRQ", { "1FRQ", "Modulator 1 frequency", "Continuous (linear) frequency of modulator 1." } },
		{ 10, "1FEN", { "1FEN", "Modulator 1 frequency envelope", "Speed and depth of an envelope added to 1FRQ on every note." } },
		{ 10, "1VOL", { "1VOL", "Modulator 1 level & feedback", "Output level of the first FM block. High values add feedback." } },
		{ 10, "1VEN", { "1VEN", "Modulator 1 level envelope", "Speed and depth of an envelope added to modulator 1's level on every note." } },
		{ 10, "2FRQ", { "2FRQ", "Modulator 2 frequency", "Continuous (exponential) frequency of modulator 2." } },
		{ 10, "2ENV", { "2ENV", "Modulator 2 level & envelope", "Output level of the second FM block, as a combined level and envelope: 0 to 64 is a steady level (64 = full). Above 64 it starts at full and decays on every note, faster towards 127." } },
		{ 10, "2FB", { "2FB", "Modulator 2 feedback", "Feedback of modulator 2." } },
		{ 10, "TUNE", { "TUNE", "Tune", "Sets the tuning of the output." } },

		// VO-6
		{ 11, "VOC1", { "VOC1", "Vowel formant 1", "First vowel formant frequency. VOC1 and VOC2 together can make any vowel." } },
		{ 11, "VOC2", { "VOC2", "Vowel formant 2", "Second vowel formant frequency." } },
		{ 11, "V-SW", { "V-SW", "Vowel switch", "Turns the vowel off, for words ending in a consonant. Without a consonant the vowel always plays." } },
		{ 11, "VOIC", { "VOIC", "Voice type", "From normal voice to a whisper." } },
		{ 11, "CONS", { "CONS", "Consonant", "The consonant each trig starts with. '-' starts straight on the vowel." } },
		{ 11, "CLEN", { "CLEN", "Consonant length", "How long the consonant lasts. Not every consonant responds." } },
		{ 11, "CVOL", { "CVOL", "Consonant volume", "How loud the consonant is, for more or less emphatic speech. Not every consonant responds." } },
		{ 11, "TUNE", { "TUNE", "Tune", "Sets the tuning of the output." } },

		// FX-THRU
		{ 12, "INP", { "INP", "Input level", "Amplifies the incoming audio, which then passes through the track effects." } },

		// FX-REVERB
		{ 13, "DEC", { "DEC", "Decay", "How long the reverb lasts before dying out." } },
		{ 13, "DAMP", { "DAMP", "Damping", "How 'soft' the walls are: higher values make some frequencies fade faster." } },
		{ 13, "GATE", { "GATE", "Gate time", "Cuts the reverb when the signal is quiet for this long. Maximum turns the gate off." } },
		{ 13, "MIX", { "MIX", "Mix", text::mix } },
		{ 13, "HP", { "HP", "High-pass filter", "High-pass filtering of the reverb signal." } },
		{ 13, "LP", { "LP", "Low-pass filter", "Low-pass filtering of the reverb signal." } },
		{ 13, "INP", { "INP", "Input level", text::input } },

		// SWAVE-ENS
		{ 14, "PCH2", { "PCH2", "Chord note 2", text::pitchOffset } },
		{ 14, "PCH3", { "PCH3", "Chord note 3", text::pitchOffset } },
		{ 14, "PCH4", { "PCH4", "Chord note 4", text::pitchOffset } },
		{ 14, "WAVE", { "WAVE", "Waveform", "Oscillator shape, blended from two saws: from sawtooth through square to spikes." } },
		{ 14, "PW", { "PW", "Pulse width", "Mutates the sound; the result depends on WAVE. Centre turns a saw into a square." } },
		{ 14, "CHRL", { "CHRL", "Chorus level", "Level of the ensemble chorus." } },
		{ 14, "CHRW", { "CHRW", "Chorus width", "Width of the ensemble chorus." } },
		{ 14, "TUNE", { "TUNE", "Tune", "Sets the tuning of the oscillators." } },

		// FX-CHORUS
		{ 15, "DEL", { "DEL", "Delay", "Delay time of the chorus taps." } },
		{ 15, "DEP", { "DEP", "Depth", "Depth of the modulation on the chorus taps." } },
		{ 15, "SPD", { "SPD", "Speed", "Speed of the modulation on the chorus taps." } },
		{ 15, "MIX", { "MIX", "Mix", "Dry/wet balance. The middle is usually best, where the chorus interacts with the original." } },
		{ 15, "FB", { "FB", "Feedback", "Feedback of the delay taps." } },
		{ 15, "WID", { "WID", "Stereo width", "Stereo width of the chorus output." } },
		{ 15, "LP", { "LP", "Low-pass filter", "Low-pass filtering of the feedback signal." } },
		{ 15, "INP", { "INP", "Input level", text::input } },

		// FX-DYNAMIX
		{ 16, "ATK", { "ATK", "Attack", "Compressor attack time, from 0.5 ms to 100 ms." } },
		{ 16, "REL", { "REL", "Release", "Compressor release time, from 50 ms to 5 s." } },
		{ 16, "THRS", { "THRS", "Threshold", "The level where compression starts." } },
		{ 16, "MIX", { "MIX", "Mix", text::mix } },
		{ 16, "RAT", { "RAT", "Ratio", "Compression ratio, from 1:1 (none) to 1:255 (limiting)." } },
		{ 16, "GAIN", { "GAIN", "Makeup gain", "Raises the output level after compression." } },
		{ 16, "RMS", { "RMS", "RMS speed", "0 reacts to peaks; higher values follow the overall energy instead of quick spikes." } },
		{ 16, "INP", { "INP", "Input level", text::input } },

		// FX-RINGMOD
		{ 17, "WAVE", { "WAVE", "Carrier waveform", "Shape of the internal carrier: 0 is a sine, 127 a triangle." } },
		{ 17, "EXT", { "EXT", "External amount", "How much of the incoming audio is ring-modulated with the carrier." } },
		{ 17, "MIX", { "MIX", "Mix", text::mix } },
		{ 17, "INP", { "INP", "Input level", text::input } },

		// FX-PHASER
		{ 18, "CNTR", { "CNTR", "Centre", "Centre point of the phase sweep." } },
		{ 18, "DEP", { "DEP", "Depth", "Depth of the phase sweep." } },
		{ 18, "SPD", { "SPD", "Speed", "Speed of the phase sweep." } },
		{ 18, "MIX", { "MIX", "Mix", text::mix } },
		{ 18, "FB", { "FB", "Feedback", "Feedback of the processed signal." } },
		{ 18, "WID", { "WID", "Stereo width", "Stereo width of the effect." } },
		{ 18, "INP", { "INP", "Input level", text::input } },

		// FX-FLANGER
		{ 19, "DEL", { "DEL", "Delay", "Delay time of the flanged signal." } },
		{ 19, "DEP", { "DEP", "Depth", "Depth of the flanger." } },
		{ 19, "SPD", { "SPD", "Speed", "Speed of the flanger." } },
		{ 19, "MIX", { "MIX", "Mix", text::mix } },
		{ 19, "FB", { "FB", "Feedback", "Feedback of the processed signal." } },
		{ 19, "WID", { "WID", "Stereo width", "Stereo width of the effect." } },
		{ 19, "INP", { "INP", "Input level", text::input } },

		// DPRO-DDRW
		{ 32, "WAV1", { "WAV1", "Waveform 1", "First of the two waveforms, from 8 banks of 8. Top dots show the bank, bottom dots the waveform." } },
		{ 32, "MIX", { "MIX", "Mix", "Volume balance between the two waveforms." } },
		{ 32, "WAV2", { "WAV2", "Waveform 2", "Second waveform, from 8 banks of 8. Top dots show the bank, bottom dots the waveform." } },
		{ 32, "TIME", { "TIME", "Glide time", "How slowly a waveform change blends in. 0 switches instantly." } },
		{ 32, "BR1", { "BR1", "Bit reduction 1", "Bit reduction applied to WAV1." } },
		{ 32, "WID", { "WID", "Width", "Pitch distance between the two waveforms." } },
		{ 32, "BR2", { "BR2", "Bit reduction 2", "Bit reduction applied to WAV2." } },
		{ 32, "TUNE", { "TUNE", "Tune", text::tune } },

		// DPRO-DENS
		{ 33, "PCH2", { "PCH2", "Chord note 2", text::pitchOffset } },
		{ 33, "PCH3", { "PCH3", "Chord note 3", text::pitchOffset } },
		{ 33, "PCH4", { "PCH4", "Chord note 4", text::pitchOffset } },
		{ 33, "WAVE", { "WAVE", "Waveform", "The DigiPRO waveform the chord is built from." } },
		{ 33, "CHRL", { "CHRL", "Chorus level", "Level of the ensemble chorus." } },
		{ 33, "CHRW", { "CHRW", "Chorus width", "Width of the ensemble chorus." } },
		{ 33, "TUNE", { "TUNE", "Tune", "Sets the tuning of the oscillators." } },
	};

	// Values an LFO page shows as text under the knob. Captured with mdmmLcdCapture (mode "values")
	// and checked against the owner's manual.
	inline constexpr ValueHash g_lfoTrigValues[] =
	{
		{ 0xfe136a0581c038a7ull, "FREE", "Runs continuously. Trigs never restart it." },
		{ 0x01dc17f9cdc8c639ull, "TRIG", "Restarts on every trig, then keeps running." },
		{ 0xa68751bc2df4b213ull, "HOLD", "Runs in the background; each trig freezes its level until the next trig." },
		{ 0x5159b2ac95069d5cull, "ONE",  "Restarts on each trig, runs one cycle, then holds the last level." },
		{ 0x889fd32c3ec0e9e8ull, "HALF", "Restarts on each trig, runs half a cycle, then holds the last level." },
	};
	inline constexpr ValueHash g_lfoWaveValues[] =
	{
		{ 0x057e3ce758b77cf8ull, "TRI",  "Triangle." },
		{ 0xccd380486250ca79ull, "ITRI", "Triangle, mirrored." },
		{ 0x8d8acaad854fec9dull, "SAW",  "Sawtooth." },
		{ 0x29a9e2070dd730a0ull, "ISAW", "Sawtooth, mirrored." },
		{ 0x062a4abc716c6c76ull, "SQR",  "Square." },
		{ 0x58018fc0f16b7c5full, "ISQR", "Square, mirrored." },
		{ 0x33f579c5356634b9ull, "EXP",  "Exponential decay." },
		{ 0x7ee94dc9a0e27f48ull, "IEXP", "Exponential decay, mirrored." },
		{ 0xaf5b35bc85033d29ull, "RMP",  "Ramp." },
		{ 0x52ef14b1eb1d096cull, "IRMP", "Ramp, mirrored." },
		{ 0x8504d268d03033eeull, "RND",  "Random: a new level each cycle." },
	};
	inline constexpr ValueHash g_lfoMultValues[] =
	{
		{ 0x1e4beb60aec1b5fcull, "1X",  "SPD as set." },
		{ 0x5d912bbe93b2d5ebull, "2X",  "Twice as fast as SPD alone." },
		{ 0x1e800b059d3d5c21ull, "4X",  "Four times as fast as SPD alone." },
		{ 0x5c1b25c03da1d01bull, "8X",  "Eight times as fast as SPD alone." },
		{ 0x405a9579637aadd4ull, "16X", "Sixteen times as fast as SPD alone." },
		{ 0x93edd2a112eafe8eull, "32X", "Thirty-two times as fast as SPD alone." },
		{ 0x952ed238cc7f31a5ull, "64X", "Sixty-four times as fast as SPD alone." },
	};
	// The value shown by LFO knob _encoder (2 TRIG, 3 WAVE, 4 MULT), or nullptr.
	inline const ValueHash* lfoValueForHash(const unsigned _encoder, const uint64_t _hash)
	{
		switch(_encoder)
		{
		case 2: return parameterHelp::findByHash(g_lfoTrigValues, _hash);
		case 3: return parameterHelp::findByHash(g_lfoWaveValues, _hash);
		case 4: return parameterHelp::findByHash(g_lfoMultValues, _hash);
		default: return nullptr;
		}
	}
	// Values a machine shows as text under a SYNTHESIS knob (numeric parameters leave that line
	// blank). Captured with mdmmLcdCapture (mode "enums") and checked against the owner's manual.
	struct MachineValue
	{
		uint8_t machine;
		const char* label;
		ValueHash value;
	};
	inline constexpr MachineValue g_machineValues[] =
	{
		// GND-NOIS
		{ 2, "STON", { 0x672b72eb6a3265afull, "OFF", "ST changes the character of the noise." } },
		{ 2, "STON", { 0x5616c314c6c999b5ull,  "ON",  "ST spreads the noise across the stereo field instead." } },
		// SID-6581
		{ 3, "PWRS", { 0x672b72eb6a3265afull, "OFF", "The pulse sweep runs free." } },
		{ 3, "PWRS", { 0x5616c314c6c999b5ull,  "ON",  "Each note restarts the pulse sweep from PW." } },
		{ 3, "WAVE", { 0x057e3ce758b77cf8ull, "TRI",  "Triangle: soft and hollow." } },
		{ 3, "WAVE", { 0x8d8acaad854fec9dull, "SAW",  "Sawtooth: bright and buzzy." } },
		{ 3, "WAVE", { 0x2abd929416ea79fcull, "PULS", "Pulse, shaped by PW." } },
		{ 3, "WAVE", { 0x73f723acbd98505cull, "MIX",  "The SID chip's own mixed waveform." } },
		{ 3, "WAVE", { 0xc75acb8f0f865d31ull, "NOIS", "Noise." } },
		{ 3, "MOD",  { 0x672b72eb6a3265afull, "OFF",  "No modulation." } },
		{ 3, "MOD",  { 0xaeadebb42b82a65eull, "RING", "Ring modulation against the second frequency." } },
		{ 3, "MOD",  { 0x35b0eeb7f110332eull, "SYNC", "Hard sync to the second frequency." } },
		{ 3, "MOD",  { 0x10b7b153d8af5ae0ull, "R+S",  "Ring modulation and hard sync together." } },
		{ 3, "MSRC", { 0x6be3e7ddf7b4731bull, "MFRQ", "The second frequency comes from the MFRQ knob." } },
		{ 3, "MSRC", { 0xd8d34a886d80ba0cull, "PRCH", "The second frequency follows the note playing on the previous track, so two tracks shape this sound." } },
		// SWAVE-PULS
		{ 5, "PWRS", { 0x672b72eb6a3265afull, "OFF", "The pulse sweep runs free." } },
		{ 5, "PWRS", { 0x5616c314c6c999b5ull,  "ON",  "Each note restarts the pulse sweep from PW." } },
		// DPRO-WAVE
		{ 6, "WPRS", { 0x672b72eb6a3265afull, "OFF", "The wave phase sweep runs free." } },
		{ 6, "WPRS", { 0x5616c314c6c999b5ull,  "ON",  "Each note restarts the wave phase sweep from WP." } },
		{ 6, "SYNC", { 0x672b72eb6a3265afull, "OFF",  "No hard sync." } },
		{ 6, "SYNC", { 0xb4119762f03e5b61ull, "SFRQ", "Hard sync to the frequency set by SFRQ." } },
		{ 6, "SYNC", { 0xd8d34a886d80ba0cull, "PRCH", "Hard sync to the note playing on the previous track." } },
		// VO-6
		{ 11, "V-SW", { 0x672b72eb6a3265afull, "OFF", "The vowel is silent, for words ending on a consonant." } },
		{ 11, "V-SW", { 0x5616c314c6c999b5ull,  "ON",  "The vowel sounds after the consonant." } },
	};
	// The value the machine currently shows under knob _label, or nullptr.
	inline const ValueHash* machineValueForHash(const uint8_t _machine, const char* _label, const uint64_t _hash)
	{
		if(!_label)
			return nullptr;
		for(const auto& entry : g_machineValues)
			if(entry.machine == _machine && entry.value.hash == _hash && std::strcmp(entry.label, _label) == 0)
				return &entry.value;
		return nullptr;
	}
	inline const char* labelForHash(const uint64_t _hash)
	{
		return parameterHelp::labelForHash(g_labelHashes, _hash);
	}

	inline const Machine* machineForHash(const uint64_t _hash)
	{
		for(const auto& entry : g_machineHashes)
		{
			if(entry.hash != _hash)
				continue;
			for(const auto& machine : g_machines)
				if(machine.id == entry.machine)
					return &machine;
		}
		return nullptr;
	}

	inline const parameterHelp::Entry* parameter(const uint8_t _machine, const char* const _label)
	{
		for(const auto& p : g_parameters)
			if(p.machine == _machine && std::strcmp(p.label, _label) == 0)
				return &p.entry;
		return nullptr;
	}

	inline const LfoPage* lfoPageForHash(const uint64_t _hash)
	{
		return parameterHelp::findByHash(g_lfoPages, _hash);
	}

	inline const parameterHelp::Entry* lfoSpecialDestinationForHash(const uint64_t _hash)
	{
		for(const auto& entry : g_lfoSpecialDestinationHashes)
		{
			if(entry.hash != _hash)
				continue;
			for(const auto& destination : g_lfoSpecialDestinations)
				if(std::strcmp(destination.abbreviation, entry.label) == 0)
					return &destination;
		}
		return nullptr;
	}

	// The fixed-page help entry whose LCD label is _label, if _dataPage is AMP..LFO 3.
	inline const parameterHelp::Entry* fixedPageEntry(const int _dataPage, const char* const _label)
	{
		const auto* const page = parameterHelp::monomachinePage(_dataPage);
		return page ? parameterHelp::entryForLabel(*page, _label) : nullptr;
	}
}
