#include "mdLib/mdhardware.h"
#include "mdLib/mdromloader.h"
#include "mdLib/mdsysexautomation.h"
#include "baseLib/filesystem.h"

#include <algorithm>
#include <cstdlib>
#include <iostream>
#include <memory>
#include <stdexcept>

namespace
{
	void require(const bool condition, const char* message)
	{
		if(!condition)
			throw std::runtime_error(message);
	}

	void advance(md::Hardware& hardware, const uint32_t frames)
	{
		for(uint32_t done = 0; done < frames;)
		{
			const auto chunk = std::min<uint32_t>(256, frames - done);
			hardware.advance(chunk);
			done += chunk;
		}
	}
}

int main()
{
	const auto* path = std::getenv("GEARMULATOR_MM_FIRMWARE_BIN");
	if(!path || !*path)
	{
		std::cout << "mmBootFirmwareTest: SKIP (MM firmware not supplied)\n";
		return 77;
	}
	try
	{
		constexpr auto model = md::MachineModel::Monomachine;
		std::vector<uint8_t> rom;
		require(baseLib::filesystem::readFile(rom, path), "could not read MM fixture");
		require(md::RomLoader::isRomForModel(rom, model), "MM fixture fingerprint mismatch");
		auto machine = std::make_unique<md::Hardware>(rom, path, model);
		auto& hardware = *machine;
		advance(hardware, md::g_samplerate * 20);
		require(hardware.isAudioReady(), "MM DSPs did not finish boot");
		require(hardware.isFirmwareMidiReady(), "MM panel/MIDI startup did not complete");

		// Require a response generated by firmware through the emulated MIDI UART.
		// A finite/silent audio buffer alone cannot prove that boot completed.
		std::vector<synthLib::SMidiEvent> events;
		hardware.readMidiOut(events);
		synthLib::SMidiEvent request(synthLib::MidiEventSource::Host);
		const auto bytes = md::automation::sysex::statusRequest(model,
			md::automation::sysex::StatusParameter::Kit);
		request.sysex.assign(bytes.begin(), bytes.end());
		require(hardware.sendMidi(request), "MM rejected status request");
		for(uint32_t attempt = 0; attempt < 20; ++attempt)
		{
			advance(hardware, md::g_samplerate / 10);
			events.clear();
			hardware.readMidiOut(events);
			for(const auto& event : events)
				if(const auto response = md::automation::sysex::parseStatusResponse(model, event.sysex))
					if(response->parameter == md::automation::sysex::StatusParameter::Kit)
					{
						std::cout << "mmBootFirmwareTest: PASS, firmware reports kit "
							<< unsigned(response->value) << '\n';
						return 0;
					}
		}
		throw std::runtime_error("MM firmware did not answer kit status request");
	}
	catch(const std::exception& error)
	{
		std::cerr << "mmBootFirmwareTest: " << error.what() << '\n';
		return 1;
	}
}
