#include "mdLib/mdhardware.h"
#include "mdLib/mdromloader.h"
#include "mdLib/mdsysexautomation.h"
#include "baseLib/filesystem.h"

#include <algorithm>
#include <cstdlib>
#include <iostream>
#include <memory>
#include <stdexcept>

namespace
{
	void require(const bool condition, const char* message)
	{
		if(!condition)
			throw std::runtime_error(message);
	}

	void advance(md::Hardware& hardware, const uint32_t frames)
	{
		for(uint32_t done = 0; done < frames;)
		{
			const auto chunk = std::min<uint32_t>(256, frames - done);
			hardware.advance(chunk);
			done += chunk;
		}
	}

	bool sameLcd(const md::FrontPanel& a, const md::FrontPanel& b)
	{
		for(uint32_t y = 0; y < md::FrontPanel::g_lcdHeight; ++y)
			for(uint32_t x = 0; x < md::FrontPanel::g_lcdWidth; ++x)
				if(a.getLcdPixel(x, y) != b.getLcdPixel(x, y))
					return false;
		return true;
	}

	void tap(md::Hardware& hardware, const md::PanelControl control)
	{
		const auto packet = md::panelPacket(md::MachineModel::Monomachine, control);
		require(packet.has_value(), "missing MM panel mapping");
		require(hardware.trySendPanelEvent(packet->row, packet->mask), "panel press rejected");
		advance(hardware, 2048);
		require(hardware.trySendPanelEvent(packet->row, 0), "panel release rejected");
		advance(hardware, md::g_samplerate / 2);
	}

	void testPanelProgress(md::Hardware& hardware)
	{
		// Exercise the UART panel path after boot, without inspecting firmware task
		// memory. Repeated menu entry/exit must keep producing fresh LCD content.
		for(uint32_t iteration = 0; iteration < 3; ++iteration)
		{
			const auto before = hardware.getFrontPanelSnapshot();
			tap(hardware, md::PanelControl::Tempo);
			const auto tempo = hardware.getFrontPanelSnapshot();
			require(!sameLcd(before, tempo), "MM tempo menu did not update LCD");
			tap(hardware, md::PanelControl::Exit);
			require(!sameLcd(tempo, hardware.getFrontPanelSnapshot()),
				"MM menu exit did not update LCD");
		}
	}
}

int main()
{
	const auto* path = std::getenv("GEARMULATOR_MM_FIRMWARE_BIN");
	if(!path || !*path)
	{
		std::cout << "mmBootFirmwareTest: SKIP (MM firmware not supplied)\n";
		return 77;
	}
	try
	{
		constexpr auto model = md::MachineModel::Monomachine;
		std::vector<uint8_t> rom;
		require(baseLib::filesystem::readFile(rom, path), "could not read MM fixture");
		require(md::RomLoader::isRomForModel(rom, model), "MM fixture fingerprint mismatch");
		auto machine = std::make_unique<md::Hardware>(rom, path, model);
		auto& hardware = *machine;
		advance(hardware, md::g_samplerate * 20);
		require(hardware.isAudioReady(), "MM DSPs did not finish boot");
		require(hardware.isFirmwareMidiReady(), "MM panel/MIDI startup did not complete");

		// Require a response generated by firmware through the emulated MIDI UART.
		// A finite/silent audio buffer alone cannot prove that boot completed.
		std::vector<synthLib::SMidiEvent> events;
		hardware.readMidiOut(events);
		synthLib::SMidiEvent request(synthLib::MidiEventSource::Host);
		const auto bytes = md::automation::sysex::statusRequest(model,
			md::automation::sysex::StatusParameter::Kit);
		request.sysex.assign(bytes.begin(), bytes.end());
		require(hardware.sendMidi(request), "MM rejected status request");
		for(uint32_t attempt = 0; attempt < 20; ++attempt)
		{
			advance(hardware, md::g_samplerate / 10);
			events.clear();
			hardware.readMidiOut(events);
			for(const auto& event : events)
				if(const auto response = md::automation::sysex::parseStatusResponse(model, event.sysex))
					if(response->parameter == md::automation::sysex::StatusParameter::Kit)
					{
						testPanelProgress(hardware);
						std::cout << "mmBootFirmwareTest: PASS, firmware reports kit "
							<< unsigned(response->value) << '\n';
						return 0;
					}
		}
		throw std::runtime_error("MM firmware did not answer kit status request");
	}
	catch(const std::exception& error)
	{
		std::cerr << "mmBootFirmwareTest: " << error.what() << '\n';
		return 1;
	}
}
